package no.sikt.graphitron.rewrite.model;

import java.util.List;

/**
 * A single WHERE-clause contribution for a SQL-generating field.
 *
 * <p>Every implementation describes one condition method call that the fetcher generator emits as
 * {@code condition = condition.and(ClassName.methodName(table, arg1, arg2, ...))}.
 * The fetcher generator uses only this interface — it does not need to know whether the method
 * was generated by Graphitron or supplied by the developer.
 *
 * <p>Two implementations:
 * <ul>
 *   <li>{@link GeneratedConditionFilter} — a condition method generated by Graphitron from
 *       argument-to-column bindings. Also carries {@link BodyParam} data consumed exclusively
 *       by {@link no.sikt.graphitron.rewrite.generators.TypeConditionsGenerator} to emit the
 *       method body.</li>
 *   <li>{@link ConditionFilter} — a developer-supplied {@code @condition} method. No generation
 *       is needed; the developer wrote the body.</li>
 * </ul>
 *
 * <p>The raw argument-classification intermediates ({@code ColumnFilter}, {@code EnumColumnFilter},
 * {@code TextEnumColumnFilter}, {@code InputFilter}) are internal to the builder and do not appear
 * in the taxonomy. The builder converts them into {@link GeneratedConditionFilter} instances,
 * validating each argument at build time before storing the result.
 */
public sealed interface WhereFilter permits GeneratedConditionFilter, ConditionFilter {

    /** Fully qualified class name of the condition method (e.g. {@code "com.example.rewrite.types.FilmConditions"}). */
    String className();

    /** Name of the condition method (e.g. {@code "filmsCondition"}). */
    String methodName();

    /**
     * The arguments to pass after the implicit table-alias first parameter, in declaration order.
     * Used by the fetcher generator to emit the call-site argument list.
     */
    List<CallParam> callParams();
}
