extend type Query @classifiedType(as: RootType) {
  film: Film @classified(source: Query, operations: [Select], target: Single, targetShape: Table)
    @commits(source: AnchorTable, result: SingleRecord)
  films: [Film!]! @asConnection @classified(source: Query, operations: [OrderBy, Paginate, Select], target: Single, targetShape: Connection)
    @commits(source: AnchorTable, result: Connection)
}

type Film @table(name: "film") @classifiedType(as: TableType) {
  title: String @classified(source: Child, operations: [Select], target: Single, targetShape: Column)
}

{
  # A single film, fetched by primary key.
  film {
    # The film's display title.
    title
  }
}
