type Country @table(name: "country") @classifiedType(as: TableType) {
  name: String @field(name: "country") @classified(source: Child, operations: [Select], target: Single, targetShape: Column)
}

type City @table(name: "city") @classifiedType(as: TableType) {
  country: Country @classified(source: OnlyChild, operations: [Join, Select], target: Single, targetShape: Table)
  countrySplit: Country @splitQuery @classified(source: OnlyChild, operations: [Join, Select], target: Single, targetShape: Table)
    @commits(source: CorrelatedChain, result: SingleRecord)
}

extend type Query {
  city: City @classified(source: Query, operations: [Select], target: Single, targetShape: Table)
    @commits(source: AnchorTable, result: SingleRecord)
}

{ city { country { name } countrySplit { name } } }
