package no.sikt.graphitron.rewrite.field;

import no.sikt.graphitron.rewrite.type.TableRef;

/**
 * Outcome of resolving the return type name of a field against the classified
 * {@link no.sikt.graphitron.rewrite.GraphitronSchema}, combined with the
 * {@link FieldWrapper} that describes how the element type is wrapped (single, list, or connection).
 *
 * <p>{@link TableBoundReturnType} — Graphitron generates the SQL query. The named type is a
 * {@link no.sikt.graphitron.rewrite.type.GraphitronType.TableType} or
 * {@link no.sikt.graphitron.rewrite.type.GraphitronType.TableInterfaceType}, or the field
 * inherits its parent's table context ({@code NestingField}). {@code table} is always a fully
 * resolved {@link no.sikt.graphitron.rewrite.type.TableRef}; when the table name in
 * {@code @table} cannot be found in the jOOQ catalog the builder classifies the containing
 * field as {@link UnclassifiedField} instead of emitting a {@link TableBoundReturnType}.
 *
 * <p>{@link OtherReturnType} — the return type is a concrete Java-backed type whose data is
 * provided by the developer (service method or record accessor), not generated by Graphitron.
 * The sealed sub-types describe the backing Java representation:
 * {@link OtherReturnType.JavaRecordReturnType} for Java {@code record} classes,
 * {@link OtherReturnType.PojoReturnType} for plain Java classes,
 * {@link OtherReturnType.JooqRecordReturnType} for jOOQ {@code Record<?>} instances, and
 * {@link OtherReturnType.JooqTableRecordReturnType} for jOOQ {@code TableRecord<?>} instances.
 * The specific sub-type is determined by reflecting on the backing class at parse time.
 *
 * <p>{@link PolymorphicReturnType} — stub for multi-table polymorphic returns (GraphQL interfaces
 * and unions whose members are each backed by separate tables, and Relay/Federation built-in
 * fields). Code generation for this case is not yet implemented.
 */
public sealed interface ReturnTypeRef
    permits ReturnTypeRef.TableBoundReturnType, ReturnTypeRef.OtherReturnType, ReturnTypeRef.PolymorphicReturnType {

    String returnTypeName();

    /** The wrapper around the element type — {@link FieldWrapper.Single}, {@link FieldWrapper.List}, or {@link FieldWrapper.Connection}. */
    FieldWrapper wrapper();

    /**
     * Graphitron generates the SQL query. The named type is a table-backed type
     * or the field inherits its parent's table context.
     * {@code table} is the outcome of resolving the type's {@code @table} directive.
     */
    record TableBoundReturnType(String returnTypeName, TableRef table, FieldWrapper wrapper) implements ReturnTypeRef {}

    /**
     * The return type is a concrete Java-backed type provided by the developer.
     * The sub-type identifies the backing Java representation.
     */
    sealed interface OtherReturnType extends ReturnTypeRef
        permits OtherReturnType.JavaRecordReturnType, OtherReturnType.PojoReturnType,
                OtherReturnType.JooqRecordReturnType, OtherReturnType.JooqTableRecordReturnType {

        /** The backing class is a Java {@code record}. */
        record JavaRecordReturnType(String returnTypeName, FieldWrapper wrapper) implements OtherReturnType {}

        /** The backing class is a plain Java class (POJO). */
        record PojoReturnType(String returnTypeName, FieldWrapper wrapper) implements OtherReturnType {}

        /** The backing class is a jOOQ {@code Record<?>} (not table-bound). */
        record JooqRecordReturnType(String returnTypeName, FieldWrapper wrapper) implements OtherReturnType {}

        /**
         * The backing class is a jOOQ {@code TableRecord<?>}.
         * {@code table} is the resolved table this record is bound to.
         */
        record JooqTableRecordReturnType(String returnTypeName, TableRef table, FieldWrapper wrapper) implements OtherReturnType {}
    }

    /**
     * Stub for multi-table polymorphic returns: GraphQL interfaces and unions whose member types
     * are each backed by separate tables, and Relay/Federation built-in fields ({@code node},
     * {@code _entities}). Code generation for this case is not yet implemented.
     */
    record PolymorphicReturnType(String returnTypeName, FieldWrapper wrapper) implements ReturnTypeRef {}
}
