ALTER TABLE CUSTOMER ADD COLUMN IF NOT EXISTS USERNAMES TEXT[];
ALTER TABLE CUSTOMER ADD COLUMN IF NOT EXISTS PAST_ADDRESS_IDS INTEGER[];

UPDATE CUSTOMER SET USERNAMES = ARRAY['user1', 'user2'] WHERE CUSTOMER_ID = 1;
UPDATE CUSTOMER SET USERNAMES = ARRAY[]::TEXT[] WHERE CUSTOMER_ID = 2;
UPDATE CUSTOMER SET USERNAMES = ARRAY['MyUsername'] WHERE CUSTOMER_ID = 3;

UPDATE CUSTOMER SET PAST_ADDRESS_IDS = ARRAY[2, 3] WHERE CUSTOMER_ID = 1;
UPDATE CUSTOMER SET PAST_ADDRESS_IDS = ARRAY[]::INTEGER[] WHERE CUSTOMER_ID = 2;
UPDATE CUSTOMER SET PAST_ADDRESS_IDS = ARRAY[4] WHERE CUSTOMER_ID = 3;