package no.sikt.graphitron.rewrite.classifieddsl;

import no.sikt.graphitron.rewrite.ArchitectureDocSymbolScanner;
import no.sikt.graphitron.rewrite.classifieddsl.CorpusDocuments.Document;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Set;

/**
 * One worked example, whole: the SDL a document's projection renders to, and the outcome table
 * saying what the pipeline makes of those coordinates. The unit the documentation page includes and
 * the unit an approval holds.
 *
 * <p><b>Why one artifact and not two.</b> The two halves used to be pasted onto the page separately
 * and held there by a test each, the page being the only place either expectation lived. Collapsing
 * that leaves a choice about where each half goes, and the halves answer it differently: the
 * verdicts are asserted in the document's own {@code @expectEquals} blocks and need no second home,
 * while the emitted unit and method names are not a store fact and are pinned nowhere else in the
 * tree. A fragment holding only the verdict half could be generated and never committed; one
 * holding the emitted names is an approval and has to be checked in to be one. So the fragment is
 * committed, and being committed it can serve the page directly: the approval file and the include
 * target are the same file, written once by {@link CorpusFragmentTest}.
 *
 * <p><b>Committed rather than staged, and what that buys.</b> The alternative was rendering into the
 * docs module's staging tree at build time, which fails on its own terms here: the renderer captures
 * and generates, so it needs the corpus's reflection stubs, and those live in this module's test tree
 * behind {@code maven.test.skip}. A staged fragment would therefore be absent from exactly the
 * builds that skip tests while the page's {@code include::} stayed unconditional. A committed
 * fragment is present in every build, and the approval comparison is what keeps it honest. This is
 * the contract {@code roadmap/README.md} already has: generated, committed, never hand-edited, and
 * regenerated by the tool that owns it.
 *
 * <p><b>The marker is the file's, not the block's.</b> {@link ArchitectureDocSymbolScanner} skips a
 * generated region from its marker to the close of the table inside it, so one marker at the head of
 * the fragment covers both halves. That is also the line telling a human not to edit the file.
 */
final class CorpusFragmentRenderer {

    /**
     * The fragment's first line: the scanner's region marker plus the reason not to hand-edit.
     * Deliberately the whole line rather than a prefix, so a stale marker cannot pass for a fresh
     * one.
     */
    static final String HEADER = ArchitectureDocSymbolScanner.GENERATED_BLOCK_MARKER
        + " Do not edit; CorpusFragmentTest writes it.";

    /** Where the fragments live, relative to the documentation root, and the include's own text. */
    private static final String PAGE_DIRECTORY = "docs/architecture/reference";

    /**
     * The documentation root, resolved from either the reactor root or a module directory the way
     * {@link CorpusDocuments} resolves the corpus folder.
     */
    private static final List<Path> ROOT_CANDIDATES = List.of(Path.of(".."), Path.of("."));

    private CorpusFragmentRenderer() {}

    /**
     * The fragment for one document, ready to be written or compared. Needs a directory to capture
     * and generate in; callers pass a JUnit temp directory.
     */
    static String render(Document document, Path workDir) throws IOException {
        return HEADER + "\n"
            + "[source,graphql]\n"
            + "----\n"
            + QueryViewRenderer.render(document.sdl(), document.projection()) + "\n"
            + "----\n"
            + "\n"
            + OutcomeBlockRenderer.render(document, workDir);
    }

    /** The fragment file's name, which is also what an {@code include::} on the page spells. */
    static String fileName(String id) {
        return "_example-" + id + ".adoc";
    }

    /** The include line a page carries for {@code id}, verbatim. */
    static String includeLine(String id) {
        return "include::" + fileName(id) + "[]";
    }

    /** Where {@code id}'s fragment is committed. */
    static Path fragmentFile(String id) {
        return directory().resolve(fileName(id));
    }

    /**
     * The directory holding the fragments and the page that includes them. The two share a directory
     * on purpose: a relative {@code xref:} written inside a fragment then resolves identically
     * whether it is read as part of the including page or on its own, which is what the staged-site
     * xref check reads it as.
     */
    static Path directory() {
        return ROOT_CANDIDATES.stream()
            .map(root -> root.resolve(PAGE_DIRECTORY))
            .filter(Files::isDirectory)
            .findFirst()
            .orElseThrow(() -> new AssertionError(
                "could not locate " + PAGE_DIRECTORY + " from working dir "
                + Path.of("").toAbsolutePath()));
    }

    /**
     * Where a disagreeing render is left for a human to look at: under this module's own
     * {@code target}, never beside the approved file. The fragments sit in the published
     * documentation tree, so a stray {@code .adoc} there would be staged, scanned and reported as an
     * untracked page; {@code target} is already ignored and already swept by {@code clean}.
     *
     * <p>Derived from the corpus folder rather than resolved on its own, so both directories answer
     * to the same working-directory guess: four levels up from the folder is the module, whichever
     * candidate matched.
     */
    static Path renderDirectory() throws IOException {
        Path directory = CorpusDocuments.folder()
            .resolve(Path.of("..", "..", "..", ".."))
            .normalize()
            .resolve(Path.of("target", "corpus-fragments"));
        Files.createDirectories(directory);
        return directory;
    }

    // -------------------------------------------------------------------------------------------
    // The placement floors, as functions over the three sets they compare. Taking the sets as
    // arguments is what lets each direction carry a planted regression: the sweep reads the real
    // tree, where a green run says only that nothing currently disagrees.
    // -------------------------------------------------------------------------------------------

    /** Fragments with no document behind them: a render of something the corpus no longer has. */
    static List<String> orphanFragments(List<String> committed, Set<String> documents) {
        return committed.stream().filter(id -> !documents.contains(id)).sorted().toList();
    }

    /** Documents carrying a projection with no fragment: a worked example nothing can show. */
    static List<String> missingFragments(List<String> committed, Set<String> documents) {
        Set<String> present = Set.copyOf(committed);
        return documents.stream().filter(id -> !present.contains(id)).sorted().toList();
    }

    /**
     * Fragments no authored page includes: the render cost paid and no reader served. Matched on the
     * include line verbatim rather than on the id, so a page naming the file in prose does not count
     * as showing it.
     */
    static List<String> notIncluded(List<String> committed, String authoredPages) {
        return committed.stream()
            .filter(id -> !authoredPages.contains(includeLine(id)))
            .sorted()
            .toList();
    }

    /** Every committed fragment, by the id its filename spells. */
    static List<String> committedIds() throws IOException {
        try (var files = Files.list(directory())) {
            return files.map(path -> path.getFileName().toString())
                .filter(name -> name.startsWith("_example-") && name.endsWith(".adoc"))
                .map(name -> name.substring("_example-".length(), name.length() - ".adoc".length()))
                .sorted()
                .toList();
        }
    }
}
