package no.sikt.graphitron.generators.codebuilding;

import static no.sikt.graphitron.generators.codebuilding.VariablePrefix.internalPrefix;

public class VariableNames {
    public final static String
            VAR_SELECTION_SET = internalPrefix("selectionSet"),
            VAR_IDS = internalPrefix("ids"),
            VAR_RESOLVER_KEYS = internalPrefix("keys"),
            VAR_LOOKUP_KEYS = internalPrefix("lookupKeys"),
            VAR_PAGE_SIZE = internalPrefix("pageSize"),
            VAR_CONTEXT = internalPrefix("ctx"),
            VAR_GRAPH_CONTEXT = internalPrefix("graphCtx"),
            VAR_TRANSFORMER = internalPrefix("transform"),
            VAR_ORDER_FIELDS = internalPrefix("orderFields"),
            VAR_PATH_NAME = internalPrefix("path"),
            VAR_INDEX_PATH = internalPrefix("indexPath"),
            VAR_PATH_HERE = internalPrefix("pathHere"),
            VAR_ARGS = internalPrefix("args"),
            VAR_ENV = internalPrefix("env"),
            VAR_SELECT = internalPrefix("select"),
            VAR_VALIDATION_ERRORS = internalPrefix("validationErrors"),
            VAR_PATHS_FOR_PROPERTIES = internalPrefix("pathsForProperties"),
            VAR_TYPE_NAME = internalPrefix("targetType"),
            VAR_TYPE_ID = internalPrefix("typeId"),
            VAR_FETCHER_NAME = internalPrefix("fetcher"),
            VAR_LOADER = internalPrefix("loaderName"),
            VAR_INPUT_MAP = internalPrefix("inputMap"),
            VAR_OBJECT = internalPrefix("obj"),
            VAR_RESULT = internalPrefix("result"),
            VAR_GRAPHITRON_CONTEXT = internalPrefix("graphitronContext"),
            VAR_ITERATOR = internalPrefix("it"),
            VAR_RECORD_ITERATOR = internalPrefix("r"),
            VAR_NODE_HANDLER = internalPrefix("nodeIdHandler"),
            VAR_NODE_STRATEGY = internalPrefix("nodeIdStrategy"),
            VAR_NODE_MAP = internalPrefix("TABLE_TO_TYPE"),
            GRAPHITRON_CONTEXT_NAME = "graphitronContext",
            METHOD_ARGS_NAME = "getArguments",
            METHOD_CONTEXT_NAME = "getCtx",
            METHOD_VALIDATE_NAME = "validate",
            METHOD_ENV_NAME = "getEnv",
            METHOD_SELECT_NAME = "getSelect",
            METHOD_SOURCE_NAME = "getSource",
            METHOD_GRAPH_CONTEXT = "getGraphQlContext",
            METHOD_SET_RECORD_ID = "setId",
            METHOD_SET_RECORD_REFERENCE_ID = "setReferenceId";
}
