/*
 * This file is generated by jOOQ.
 */
package no.sikt.graphitron.rewrite.test.jooq;


import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import no.sikt.graphitron.rewrite.test.jooq.tables.Address;
import no.sikt.graphitron.rewrite.test.jooq.tables.Category;
import no.sikt.graphitron.rewrite.test.jooq.tables.City;
import no.sikt.graphitron.rewrite.test.jooq.tables.Country;
import no.sikt.graphitron.rewrite.test.jooq.tables.Customer;
import no.sikt.graphitron.rewrite.test.jooq.tables.Film;
import no.sikt.graphitron.rewrite.test.jooq.tables.FilmCategory;
import no.sikt.graphitron.rewrite.test.jooq.tables.Inventory;
import no.sikt.graphitron.rewrite.test.jooq.tables.Language;
import no.sikt.graphitron.rewrite.test.jooq.tables.Payment;
import no.sikt.graphitron.rewrite.test.jooq.tables.Rental;
import no.sikt.graphitron.rewrite.test.jooq.tables.Staff;
import no.sikt.graphitron.rewrite.test.jooq.tables.Store;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * standard public schema
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.20.11",
        "schema version:1.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.address</code>.
     */
    public final Address ADDRESS = Address.ADDRESS;

    /**
     * The table <code>public.category</code>.
     */
    public final Category CATEGORY = Category.CATEGORY;

    /**
     * The table <code>public.city</code>.
     */
    public final City CITY = City.CITY;

    /**
     * The table <code>public.country</code>.
     */
    public final Country COUNTRY = Country.COUNTRY;

    /**
     * The table <code>public.customer</code>.
     */
    public final Customer CUSTOMER = Customer.CUSTOMER;

    /**
     * The table <code>public.film</code>.
     */
    public final Film FILM = Film.FILM;

    /**
     * The table <code>public.film_category</code>.
     */
    public final FilmCategory FILM_CATEGORY = FilmCategory.FILM_CATEGORY;

    /**
     * The table <code>public.inventory</code>.
     */
    public final Inventory INVENTORY = Inventory.INVENTORY;

    /**
     * The table <code>public.language</code>.
     */
    public final Language LANGUAGE = Language.LANGUAGE;

    /**
     * The table <code>public.payment</code>.
     */
    public final Payment PAYMENT = Payment.PAYMENT;

    /**
     * The table <code>public.rental</code>.
     */
    public final Rental RENTAL = Rental.RENTAL;

    /**
     * The table <code>public.staff</code>.
     */
    public final Staff STAFF = Staff.STAFF;

    /**
     * The table <code>public.store</code>.
     */
    public final Store STORE = Store.STORE;

    /**
     * No further instances allowed
     */
    private Public() {
        super(DSL.name("public"), null, DSL.comment("standard public schema"));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Address.ADDRESS,
            Category.CATEGORY,
            City.CITY,
            Country.COUNTRY,
            Customer.CUSTOMER,
            Film.FILM,
            FilmCategory.FILM_CATEGORY,
            Inventory.INVENTORY,
            Language.LANGUAGE,
            Payment.PAYMENT,
            Rental.RENTAL,
            Staff.STAFF,
            Store.STORE
        );
    }
}
