/*
 * This file is generated by jOOQ.
 */
package no.sikt.graphitron.rewrite.test.jooq;


import javax.annotation.processing.Generated;

import no.sikt.graphitron.rewrite.test.jooq.tables.Address;
import no.sikt.graphitron.rewrite.test.jooq.tables.Category;
import no.sikt.graphitron.rewrite.test.jooq.tables.City;
import no.sikt.graphitron.rewrite.test.jooq.tables.Country;
import no.sikt.graphitron.rewrite.test.jooq.tables.Customer;
import no.sikt.graphitron.rewrite.test.jooq.tables.Film;
import no.sikt.graphitron.rewrite.test.jooq.tables.FilmCategory;
import no.sikt.graphitron.rewrite.test.jooq.tables.Inventory;
import no.sikt.graphitron.rewrite.test.jooq.tables.Language;
import no.sikt.graphitron.rewrite.test.jooq.tables.Payment;
import no.sikt.graphitron.rewrite.test.jooq.tables.Rental;
import no.sikt.graphitron.rewrite.test.jooq.tables.Staff;
import no.sikt.graphitron.rewrite.test.jooq.tables.Store;


/**
 * Convenience access to all tables in public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.20.11",
        "schema version:1.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.address</code>.
     */
    public static final Address ADDRESS = Address.ADDRESS;

    /**
     * The table <code>public.category</code>.
     */
    public static final Category CATEGORY = Category.CATEGORY;

    /**
     * The table <code>public.city</code>.
     */
    public static final City CITY = City.CITY;

    /**
     * The table <code>public.country</code>.
     */
    public static final Country COUNTRY = Country.COUNTRY;

    /**
     * The table <code>public.customer</code>.
     */
    public static final Customer CUSTOMER = Customer.CUSTOMER;

    /**
     * The table <code>public.film</code>.
     */
    public static final Film FILM = Film.FILM;

    /**
     * The table <code>public.film_category</code>.
     */
    public static final FilmCategory FILM_CATEGORY = FilmCategory.FILM_CATEGORY;

    /**
     * The table <code>public.inventory</code>.
     */
    public static final Inventory INVENTORY = Inventory.INVENTORY;

    /**
     * The table <code>public.language</code>.
     */
    public static final Language LANGUAGE = Language.LANGUAGE;

    /**
     * The table <code>public.payment</code>.
     */
    public static final Payment PAYMENT = Payment.PAYMENT;

    /**
     * The table <code>public.rental</code>.
     */
    public static final Rental RENTAL = Rental.RENTAL;

    /**
     * The table <code>public.staff</code>.
     */
    public static final Staff STAFF = Staff.STAFF;

    /**
     * The table <code>public.store</code>.
     */
    public static final Store STORE = Store.STORE;
}
