package no.sikt.graphitron.mappings;

import org.jooq.Parameter;
import org.jooq.Routine;
import org.jooq.impl.AbstractRoutine;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.JarURLConnection;
import java.net.URL;
import java.util.*;
import java.util.stream.Collectors;

/**
 * Helper class that takes care of any routine reflection operations the code generator might require towards the jOOQ source.
 * Discovers and provides access to stored procedures and functions generated by jOOQ.
 * <p>
 * Routines are keyed internally by a schema-qualified name ({@code schema.SimpleClassName}, lowercased) so that routines
 * with the same name in different database schemas do not collide.
 */
public class RoutineReflection extends SchemaReflection {
    private static final Logger LOGGER = LoggerFactory.getLogger(RoutineReflection.class);

    /**
     * Routines keyed by their schema-qualified Java key: {@code schemaName.SimpleClassName}, both lowercased.
     * jOOQ guarantees uniqueness within a schema package, and we prefix the schema to disambiguate across schemas.
     */
    private static final Map<String, Routine<?>> ROUTINES_BY_QUALIFIED_KEY = discoverRoutines();

    /**
     * Multi-value index from lowercased routine database name (without schema) to the list of qualified keys that
     * match. When the list has a single entry, the routine is unambiguous by bare name; otherwise callers must
     * disambiguate by passing {@code schema.routine}.
     */
    private static final Map<String, List<String>> QUALIFIED_KEYS_BY_ROUTINE_NAME = ROUTINES_BY_QUALIFIED_KEY
            .entrySet()
            .stream()
            .collect(Collectors.groupingBy(
                    e -> e.getValue().getName().toLowerCase(),
                    () -> new TreeMap<>(String.CASE_INSENSITIVE_ORDER),
                    Collectors.mapping(Map.Entry::getKey, Collectors.toList())));

    /**
     * Resolves a user-supplied routine name against the discovered routines, returning the list of matching
     * qualified keys ({@code schema.SimpleClassName}, lowercased). The name may be bare ({@code foo}) or
     * schema-qualified ({@code my_schema.foo}). Matching is case-insensitive.
     * <p>
     * An empty list means no match; a single entry is unambiguous; multiple entries indicate the bare name is
     * ambiguous across schemas and the caller must disambiguate.
     */
    public static List<String> resolveRoutine(String userSuppliedName) {
        if (userSuppliedName == null || userSuppliedName.isBlank()) {
            return List.of();
        }

        var index = userSuppliedName.indexOf('.');
        if (index >= 0) {
            var schemaPart = userSuppliedName.substring(0, index).toLowerCase();
            var routinePart = userSuppliedName.substring(index + 1).toLowerCase();
            return QUALIFIED_KEYS_BY_ROUTINE_NAME
                    .getOrDefault(routinePart, List.of())
                    .stream()
                    .filter(key -> schemaFromProcedure(key).equals(schemaPart))
                    .toList();
        }

        return QUALIFIED_KEYS_BY_ROUTINE_NAME.getOrDefault(userSuppliedName.toLowerCase(), List.of());
    }

    /**
     * Returns the schema portion of a qualified routine key (the part before the dot).
     */
    public static String schemaFromProcedure(String qualifiedProcedure) {
        var index = qualifiedProcedure.indexOf('.');
        return index < 0 ? "" : qualifiedProcedure.substring(0, index);
    }

    private static Optional<Routine<?>> getRoutine(String qualifiedKey) {
        return Optional.ofNullable(ROUTINES_BY_QUALIFIED_KEY.get(qualifiedKey));
    }

    private static Optional<Parameter<?>> getReturnParameter(String qualifiedKey) {
        return getRoutine(qualifiedKey).map(Routine::getReturnParameter);
    }

    /**
     * @return Whether the routine is a function (has a return).
     */
    public static boolean isFunction(String qualifiedKey) {
        return getReturnParameter(qualifiedKey).isPresent();
    }

    /**
     * @return The IN parameters of the routine (excluding return).
     */
    public static List<Parameter<?>> getInParameters(String qualifiedKey) {
        return getRoutine(qualifiedKey).map(Routine::getInParameters).orElse(List.of());
    }

    /**
     * @return The OUT parameters of the routine (excluding return).
     */
    public static List<Parameter<?>> getOutParameters(String qualifiedKey) {
        return getRoutine(qualifiedKey).map(Routine::getOutParameters).orElse(List.of());
    }

    /**
     * @return The Java return type of the routine, if it is a function.
     */
    public static Optional<Class<?>> getReturnType(String qualifiedKey) {
        return getReturnParameter(qualifiedKey).map(Parameter::getType);
    }

    /**
     * Derives the fully qualified name of the generated {@code Routines} class that holds the convenience static methods
     * for the given routine. The class lives one package up from the individual routine class (the schema package).
     * <p>
     * Assumes the jOOQ convention where each routine class lives at {@code <schema>.routines.XYZ}; a routine placed
     * directly in the schema package would cause this to derive an incorrect parent package.
     *
     * @return The fully qualified class name of {@code Routines}, or empty if no such routine exists.
     */
    public static Optional<String> getRoutinesClassName(String qualifiedKey) {
        return getRoutine(qualifiedKey)
                .map(Routine::getClass)
                .map(Class::getPackageName)
                .map(pkg -> {
                    var idx = pkg.lastIndexOf('.');
                    return idx > 0 ? pkg.substring(0, idx) : pkg;
                })
                .map(it -> it + ".Routines");
    }

    /**
     * Derives the name of the convenience static method on the generated {@code Routines} class for a given routine.
     * jOOQ emits the method as a camelCased version of the routine's Java class name (e.g. {@code InventoryHeldByCustomer}
     * becomes {@code inventoryHeldByCustomer}, and {@code _GroupConcat} becomes {@code _GroupConcat}).
     *
     * @return The method name on the generated {@code Routines} class, or empty if no such routine exists.
     */
    public static Optional<String> getRoutineMethodName(String qualifiedKey) {
        return getRoutine(qualifiedKey)
                .map(Routine::getClass)
                .map(Class::getSimpleName)
                .map(it -> {
                    // Routines whose class name starts with an underscore (e.g. _GroupConcat) keep the underscore and PascalCase in jOOQ output.
                    if (it.startsWith("_")) {
                        return it;
                    }
                    return Character.toLowerCase(it.charAt(0)) + it.substring(1);
                });
    }

    /**
     * Discovers all jOOQ-generated routine classes by scanning the {@code routines} subpackage
     * of each schema for classes extending {@link AbstractRoutine}, instantiating them to
     * access their parameter metadata. Keys each routine by {@code schemaName.SimpleClassName} (lowercased).
     */
    private static Map<String, Routine<?>> discoverRoutines() {
        var result = new LinkedHashMap<String, Routine<?>>();
        getDefaultCatalog()
                .schemaStream()
                .forEach(schema -> {
                    var schemaName = schema.getName().toLowerCase();
                    var packageName = schema.getClass().getPackageName() + ".routines";
                    findRoutineClassesInPackage(packageName).forEach(routine -> {
                        var key = schemaName + "." + routine.getClass().getSimpleName().toLowerCase();
                        var previous = result.put(key, routine);
                        if (previous != null) {
                            LOGGER.warn("Duplicate routine key '{}' encountered during discovery; keeping the last one.", key);
                        }
                    });
                });
        return Map.copyOf(result);
    }

    /**
     * Scans a package for classes extending {@link AbstractRoutine} and instantiates them.
     * Uses classloader resource scanning to discover class files both when classes live on the filesystem
     * (directory entries in the classpath) and when they are packaged in JARs.
     */
    private static List<? extends Routine<?>> findRoutineClassesInPackage(String packageName) {
        var classLoader = Thread.currentThread().getContextClassLoader();
        var path = packageName.replace('.', '/');
        var classNames = new LinkedHashSet<String>();

        try {
            var resources = classLoader.getResources(path);
            while (resources.hasMoreElements()) {
                var resource = resources.nextElement();
                var protocol = resource.getProtocol();
                if ("jar".equals(protocol)) {
                    classNames.addAll(listRoutineClassNamesFromJar(resource, path));
                } else if ("file".equals(protocol)) {
                    classNames.addAll(listRoutineClassNamesFromDirectory(resource));
                } else {
                    LOGGER.debug("Unsupported classpath protocol '{}' for package {}", protocol, packageName);
                }
            }
        } catch (Exception e) {
            LOGGER.debug("Failed to scan routine classes in package: {}", packageName, e);
            return List.of();
        }

        return classNames
                .stream()
                .map(it -> packageName + "." + it)
                .map(RoutineReflection::loadRoutineClass)
                .filter(Optional::isPresent)
                .map(Optional::get)
                .toList();
    }

    /**
     * Reads direct-entry class names from a directory-based classpath resource.
     */
    private static List<String> listRoutineClassNamesFromDirectory(URL resource) {
        try (var reader = new BufferedReader(new InputStreamReader(resource.openStream()))) {
            return reader
                    .lines()
                    .filter(it -> it.endsWith(".class"))
                    .map(it -> it.substring(0, it.length() - ".class".length()))
                    .toList();
        } catch (Exception e) {
            LOGGER.debug("Failed to read routine package from directory resource: {}", resource, e);
            return List.of();
        }
    }

    /**
     * Reads direct-entry class names from a jar-based classpath resource, matching only classes that live directly
     * within the given package path (not in a sub-package).
     */
    private static List<String> listRoutineClassNamesFromJar(URL resource, String path) {
        try {
            var connection = (JarURLConnection) resource.openConnection();
            try (var jar = connection.getJarFile()) {
                var prefix = path.endsWith("/") ? path : path + "/";
                var classNames = new ArrayList<String>();
                var entries = jar.entries();
                while (entries.hasMoreElements()) {
                    var entry = entries.nextElement();
                    var name = entry.getName();
                    if (!name.startsWith(prefix) || !name.endsWith(".class")) {
                        continue;
                    }
                    var remainder = name.substring(prefix.length());
                    if (remainder.indexOf('/') != -1) {
                        continue; // Sub-package, skip.
                    }
                    classNames.add(remainder.substring(0, remainder.length() - ".class".length()));
                }
                return classNames;
            }
        } catch (Exception e) {
            LOGGER.debug("Failed to read routine package from jar resource: {}", resource, e);
            return List.of();
        }
    }

    /**
     * Loads and instantiates a routine class if it extends {@link AbstractRoutine}.
     */
    private static Optional<Routine<?>> loadRoutineClass(String fullyQualifiedClassName) {
        try {
            var clazz = Class.forName(fullyQualifiedClassName);
            if (AbstractRoutine.class.isAssignableFrom(clazz)) {
                return Optional.of((Routine<?>) clazz.getDeclaredConstructor().newInstance());
            }
        } catch (ClassNotFoundException | NoSuchMethodException | InstantiationException | IllegalAccessException | java.lang.reflect.InvocationTargetException e) {
            LOGGER.debug("Skipping routine class that could not be loaded or instantiated: {}", fullyQualifiedClassName, e);
        }
        return Optional.empty();
    }
}
