package no.sikt.graphitron.rewrite.model;

import java.util.List;

/**
 * A single WHERE-clause contribution for a SQL-generating field.
 *
 * <p>The condition command producer reads these lists into {@code ConditionCommand} rows, and
 * every WHERE consumer emits one glue call per coordinate; no emitter reads a filter's method
 * identity any more. The authored arms carry their callee identity themselves (a
 * {@link MethodRef} into consumer code); the generated arm carries only what the glue renderer
 * needs to render its terms directly.
 *
 * <ul>
 *   <li>{@link GeneratedConditionFilter}: generated by Graphitron from argument-to-column
 *       bindings; carries {@link BodyParam} data the condition producer turns into column
 *       terms.</li>
 *   <li>{@link ConditionFilter}: a developer-supplied {@code @condition} method; the developer
 *       wrote the body.</li>
 *   <li>{@link FkTargetConditionFilter}: a developer-supplied {@code @condition} method on an
 *       FK-target {@code @nodeId} input field. The implicit first parameter is the FK-target
 *       table reached through a join path rather than the field's own table, so the glue body
 *       emits a correlated {@code EXISTS} instead of passing the coordinate's own table.</li>
 * </ul>
 */
public sealed interface WhereFilter permits GeneratedConditionFilter, ConditionFilter, FkTargetConditionFilter {

    /**
     * The arguments to pass after the implicit table-alias first parameter, in declaration order.
     */
    List<CallParam> callParams();

    /**
     * True when any binding across {@code filters} reads the request context
     * ({@link CallParam#readsRequestContext()}): the one home of the fold behind the
     * env-appending glue signature. {@link SqlGeneratingField#conditionsReadRequestContext()}
     * delegates here for the coordinate-level convenience; the participant-filter path (whose
     * filters live beside the field, not on it) folds here directly.
     */
    static boolean anyReadRequestContext(List<WhereFilter> filters) {
        return filters.stream()
            .flatMap(f -> f.callParams().stream())
            .anyMatch(CallParam::readsRequestContext);
    }
}
