package no.sikt.graphitron.roadmap;

import org.yaml.snakeyaml.Yaml;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import java.util.stream.Stream;

/**
 * Reads {@code *.md} files in the roadmap directory, parses YAML front-matter,
 * and renders a {@code README.md} that aggregates them into Active and Backlog
 * sections.
 *
 * <p>Two modes:
 * <ul>
 *   <li>{@code generate &lt;dir&gt;}: write {@code dir/README.md}.</li>
 *   <li>{@code verify &lt;dir&gt;}: exit non-zero if {@code dir/README.md} is
 *       out of date relative to the current item files.</li>
 * </ul>
 */
public final class Main {

    private static final List<String> ACTIVE_STATES = List.of("Spec", "Ready", "In Progress", "In Review");
    private static final List<String> BACKLOG_BUCKETS = List.of("architecture", "stubs", "cleanup");

    private Main() {}

    public static void main(String[] args) throws IOException {
        if (args.length < 2 || !(args[0].equals("generate") || args[0].equals("verify"))) {
            System.err.println("usage: <generate|verify> <roadmap-dir>");
            System.exit(64);
        }
        String mode = args[0];
        Path dir = Path.of(args[1]).toAbsolutePath().normalize();
        if (!Files.isDirectory(dir)) {
            System.err.println("not a directory: " + dir);
            System.exit(64);
        }

        List<Item> items = readItems(dir);
        String rendered = render(items);
        Path readme = dir.resolve("README.md");

        if (mode.equals("generate")) {
            Files.writeString(readme, rendered);
            System.out.println("wrote " + readme);
        } else {
            String existing = Files.exists(readme) ? Files.readString(readme) : "";
            if (!existing.equals(rendered)) {
                System.err.println("roadmap README.md is out of date. Regenerate with:");
                System.err.println("  mvn -pl :graphitron-rewrite-roadmap-tool exec:java");
                System.exit(1);
            }
            System.out.println("roadmap README.md is up to date.");
        }
    }

    static List<Item> readItems(Path dir) throws IOException {
        try (Stream<Path> s = Files.list(dir)) {
            return s
                .filter(p -> p.getFileName().toString().endsWith(".md"))
                .filter(p -> !p.getFileName().toString().equals("README.md"))
                .filter(p -> !p.getFileName().toString().equals("changelog.md"))
                .map(Main::readItem)
                .sorted(Comparator
                    .comparingInt((Item i) -> i.priority() == null ? Integer.MAX_VALUE : i.priority())
                    .thenComparing(Item::slug))
                .toList();
        }
    }

    static Item readItem(Path file) {
        try {
            String content = Files.readString(file);
            ParsedFile parsed = parseFrontMatter(content);
            String slug = file.getFileName().toString().replaceFirst("\\.md$", "");
            return Item.from(slug, parsed.frontMatter(), parsed.body());
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    static ParsedFile parseFrontMatter(String content) {
        if (!content.startsWith("---\n") && !content.startsWith("---\r\n")) {
            return new ParsedFile(Map.of(), content);
        }
        int afterFirst = content.indexOf('\n') + 1;
        int closing = content.indexOf("\n---", afterFirst);
        if (closing < 0) {
            throw new IllegalArgumentException("front-matter not closed");
        }
        String yaml = content.substring(afterFirst, closing);
        int bodyStart = content.indexOf('\n', closing + 4) + 1;
        if (bodyStart == 0) {
            bodyStart = content.length();
        }
        @SuppressWarnings("unchecked")
        Map<String, Object> map = (Map<String, Object>) new Yaml().load(yaml);
        return new ParsedFile(map == null ? Map.of() : map, content.substring(bodyStart));
    }

    static String render(List<Item> items) {
        StringBuilder sb = new StringBuilder();
        sb.append("# Rewrite Roadmap\n\n");
        sb.append("_Generated by `graphitron-rewrite-roadmap-tool`. ");
        sb.append("Regenerate with `mvn -pl :graphitron-rewrite-roadmap-tool exec:java` ");
        sb.append("(or `mise r roadmap`). Edit per-item `*.md` files in this directory; ");
        sb.append("never edit this file by hand._\n\n");

        sb.append("Tracks remaining generator work. ");
        sb.append("For the model taxonomy, see [Code Generation Triggers](../docs/code-generation-triggers.md). ");
        sb.append("For design principles, see [Rewrite Design Principles](../docs/rewrite-design-principles.md). ");
        sb.append("For workflow conventions, see [Workflow](../docs/workflow.md).\n\n");

        sb.append("**First time contributing?** Read in this order: ");
        sb.append("[Workflow](../docs/workflow.md), ");
        sb.append("[Rewrite Design Principles](../docs/rewrite-design-principles.md), ");
        sb.append("[Code Generation Triggers](../docs/code-generation-triggers.md). ");
        sb.append("Then read an Active plan to see the shape, and pick a Backlog item or take a Ready item from Active.\n\n");

        sb.append("---\n\n");
        renderActive(sb, items);
        sb.append("\n---\n\n");
        renderBacklog(sb, items);
        sb.append("\n---\n\n");
        sb.append("## Done\n\n");
        sb.append("See [`changelog.md`](changelog.md) for the historical record of shipped rewrite work. ");
        sb.append("Plan files are deleted on Done; git history preserves them.\n");
        return sb.toString();
    }

    private static void renderActive(StringBuilder sb, List<Item> items) {
        List<Item> active = items.stream()
            .filter(i -> ACTIVE_STATES.contains(i.status()))
            .sorted(Comparator
                .comparingInt((Item i) -> ACTIVE_STATES.indexOf(i.status()))
                .thenComparingInt(i -> i.priority() == null ? Integer.MAX_VALUE : i.priority())
                .thenComparing(Item::title))
            .toList();
        sb.append("## Active\n\n");
        if (active.isEmpty()) {
            sb.append("_(none)_\n");
            return;
        }
        sb.append("| Item | Status | Plan |\n|---|---|---|\n");
        for (Item i : active) {
            String status = i.status() + (i.deferred() ? " (deferred)" : "");
            String item = i.title();
            if (i.notes() != null && !i.notes().isBlank()) {
                item += " <sub>" + i.notes().strip() + "</sub>";
            }
            sb.append("| ").append(item).append(" | ")
              .append(status).append(" | [plan](")
              .append(i.slug()).append(".md) |\n");
        }
    }

    private static void renderBacklog(StringBuilder sb, List<Item> items) {
        sb.append("## Backlog\n\n");
        List<Item> backlog = items.stream()
            .filter(i -> "Backlog".equals(i.status()))
            .toList();
        if (backlog.isEmpty()) {
            sb.append("_(none)_\n");
            return;
        }
        for (String bucket : BACKLOG_BUCKETS) {
            List<Item> b = backlog.stream()
                .filter(i -> bucket.equals(i.bucket()))
                .sorted(Comparator
                    .comparingInt((Item i) -> i.priority() == null ? Integer.MAX_VALUE : i.priority())
                    .thenComparing(Item::title))
                .toList();
            if (b.isEmpty()) {
                continue;
            }
            sb.append("### ").append(capitalize(bucket)).append("\n\n");
            for (Item i : b) {
                appendBacklogLine(sb, i);
            }
            sb.append("\n");
        }

        List<Item> orphans = backlog.stream()
            .filter(i -> i.bucket() == null || !BACKLOG_BUCKETS.contains(i.bucket()))
            .sorted(Comparator.comparing(Item::title))
            .toList();
        if (!orphans.isEmpty()) {
            sb.append("### Other\n\n");
            for (Item i : orphans) {
                appendBacklogLine(sb, i);
            }
            sb.append("\n");
        }
    }

    private static void appendBacklogLine(StringBuilder sb, Item i) {
        sb.append("- [**").append(i.title()).append("**](").append(i.slug()).append(".md)");
        String description = firstNonHeadingParagraph(i.body());
        if (!description.isEmpty()) {
            sb.append(": ").append(description);
        }
        sb.append("\n");
    }

    private static String firstNonHeadingParagraph(String body) {
        String trimmed = body.strip();
        if (trimmed.isEmpty()) {
            return "";
        }
        for (String para : trimmed.split("\n\n+")) {
            String stripped = para.strip();
            if (stripped.isEmpty()) {
                continue;
            }
            if (stripped.startsWith("#")) {
                continue;
            }
            return stripped.replace("\n", " ");
        }
        return "";
    }

    private static String capitalize(String s) {
        return Character.toUpperCase(s.charAt(0)) + s.substring(1);
    }

    record ParsedFile(Map<String, Object> frontMatter, String body) {}

    record Item(String slug, String title, String status, String bucket,
                Integer priority, boolean deferred, String notes, String body) {

        static Item from(String slug, Map<String, Object> fm, String body) {
            String title = (String) fm.getOrDefault("title", slug);
            String status = (String) fm.getOrDefault("status", "Backlog");
            String bucket = (String) fm.get("bucket");
            Integer priority = fm.get("priority") instanceof Integer p ? p : null;
            boolean deferred = Boolean.TRUE.equals(fm.get("deferred"));
            String notes = (String) fm.get("notes");
            return new Item(slug, title, status, bucket, priority, deferred, notes, body);
        }
    }
}
