package no.sikt.graphitron.rewrite.generators;


import no.sikt.graphitron.javapoet.TypeSpec;
import no.sikt.graphitron.rewrite.model.GraphitronField;
import no.sikt.graphitron.rewrite.model.GraphitronType;

import javax.lang.model.element.Modifier;
import java.util.Comparator;
import java.util.List;
import java.util.Map;

/**
 * Generates a {@link TypeSpec} for one {@code <TypeName>Fields} class in {@code rewrite.types}.
 *
 * <p>Currently an empty placeholder. This class will be renamed to {@code *References} and
 * populated with reference fields that continue the current SQL scope via subselects once
 * the relevant model types are implemented.
 *
 * <p>All field-level data fetchers (column fields, query fields, DataLoader-backed service and
 * split-query fields) live in the corresponding {@code *Fetchers} class generated by
 * {@link TypeFetcherClassGenerator}.
 */
public class TypeFieldsGenerator {

    public static List<TypeSpec> generate(no.sikt.graphitron.rewrite.GraphitronSchema schema) {
        return schema.types().entrySet().stream()
            .filter(e -> e.getValue() instanceof GraphitronType.TableType
                      || e.getValue() instanceof GraphitronType.NodeType
                      || e.getValue() instanceof GraphitronType.RootType)
            .map(java.util.Map.Entry::getKey)
            .sorted()
            .map(TypeFieldsGenerator::generateForType)
            .toList();
    }

    static TypeSpec generateForType(String typeName) {
        return TypeSpec.classBuilder(typeName + "Fields")
            .addModifiers(Modifier.PUBLIC)
            .build();
    }
}
