[tools]
maven = "3.9.9"
java = "21"

[tasks.clean]
description = "Maven clean on graphitron-example"
run = "mvn clean -Pinclude-graphitron-example"

[tasks.build]
description = "Run maven install on graphitron-example"
run = "mvn install -Pinclude-graphitron-example"

[tasks.start]
description = "Start graphitron-example-server (quarkus:dev)"
run = "mvn quarkus:dev -pl :graphitron-example-server"