services:
  postgres:
    image: sakiladb/postgres:latest
    container_name: sakila_postgres
    environment:
      POSTGRES_USER: sakila
      POSTGRES_PASSWORD: p_ssW0rd
      POSTGRES_DB: sakila
    ports:
    - "5432:5432"
