/*
 * This file is generated by jOOQ.
 */
package no.sikt.jooq.example;

import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class VacationDestination extends TableImpl<VacationDestinationRecord> {
    public static final VacationDestination VACATION_DESTINATION = new VacationDestination();

    public final TableField<VacationDestinationRecord, Long> DESTINATION_ID = createField(DSL.name("destination_id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");
    public final TableField<VacationDestinationRecord, String> COUNTRY_NAME = createField(DSL.name("country_name"), SQLDataType.VARCHAR(45).nullable(false), this, "");
    public final TableField<VacationDestinationRecord, Long> VACATION_ID = createField(DSL.name("vacation_id"), SQLDataType.BIGINT, this, "");
    public final TableField<VacationDestinationRecord, Long> EXTRA_KEY = createField(DSL.name("extra_key"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    public VacationDestination() {
        super(DSL.name("vacation_destination"), null, null, null, DSL.comment(""), TableOptions.table(), null);
    }

    @Override
    public UniqueKey<VacationDestinationRecord> getPrimaryKey() {
        return Keys.VACATION_DESTINATION_PKEY;
    }

}
