/*
 * This file is generated by jOOQ.
 */
package no.sikt.jooq.example;

import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

public class Vacation extends TableImpl<VacationRecord> {
    public static final Vacation VACATION = new Vacation();

    public final TableField<VacationRecord, Long> VACATION_ID = createField(DSL.name("vacation_id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");
    public final TableField<VacationRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(45).nullable(false), this, "");
    public final TableField<VacationRecord, Long> EXTRA_KEY = createField(DSL.name("extra_key"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    public Vacation() {
        super(DSL.name("vacation"), null, null, null, DSL.comment(""), TableOptions.table(), null);
    }

    @Override
    public UniqueKey<VacationRecord> getPrimaryKey() {
        return Keys.VACATION_PKEY;
    }
}
