/*
 * This file is generated by jOOQ.
 */
package no.sikt.jooq.example;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import java.io.Serial;

@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class VacationRecord extends UpdatableRecordImpl<VacationRecord> {
    @Serial
    private static final long serialVersionUID = 1L;

    public void setVacationId(Long value) {
        set(0, value);
    }

    public Long getVacationId() {
        return (Long) get(0);
    }

    public void setDescription(String value) {
        set(1, value);
    }

    public String getDescription() {
        return (String) get(1);
    }

    public void setExtraKey(Long value) {
        set(2, value);
    }

    public Long getExtraKey() {
        return (Long) get(2);
    }

    public VacationRecord() {
        super(Vacation.VACATION);
    }

    public VacationRecord(Long vacationId, String description) {
        super(Vacation.VACATION);
        setVacationId(vacationId);
        setDescription(description);
        resetTouchedOnNotNull();
    }

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }
}
