/*
 * This file is generated by jOOQ.
 */
package no.sikt.jooq.example;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;

import java.io.Serial;

@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class VacationDestinationRecord extends UpdatableRecordImpl<VacationDestinationRecord> {
    @Serial
    private static final long serialVersionUID = 1L;

    public void setDestinationId(Long value) {
        set(0, value);
    }

    public Long getDestinationId() {
        return (Long) get(0);
    }

    public void setCountryName(Long value) {
        set(1, value);
    }

    public String getCountryName() {
        return (String) get(1);
    }

    public void setVacationId(Long value) {
        set(2, value);
    }

    public Long getVacationId() {
        return (Long) get(2);
    }

    public void setExtraKey(Long value) {
        set(3, value);
    }

    public Long getExtraKey() {
        return (Long) get(3);
    }

    public VacationDestinationRecord() {
        super(VacationDestination.VACATION_DESTINATION);
    }

    @Override
    public Record2<Long, String> key() {
        return (Record2) super.key();
    }
}
