package no.sikt.graphitron.rewrite;

import no.sikt.graphitron.rewrite.model.CallSiteCompaction;
import no.sikt.graphitron.rewrite.model.CallSiteExtraction;
import no.sikt.graphitron.rewrite.model.ChildField;
import no.sikt.graphitron.rewrite.model.ColumnRef;
import no.sikt.graphitron.rewrite.model.GraphitronField;
import no.sikt.graphitron.rewrite.model.GraphitronType;
import no.sikt.graphitron.rewrite.model.InputField;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.EnumSource;

import java.nio.file.Path;
import java.util.List;
import java.util.Map;
import java.util.function.Consumer;

import static no.sikt.graphitron.common.configuration.TestConfiguration.DEFAULT_OUTPUT_PACKAGE;
import static org.assertj.core.api.Assertions.assertThat;
import no.sikt.graphitron.rewrite.test.tier.PipelineTier;

/**
 * SDL → classified-variant pipeline tests for the node-id path. Exercises the input-side
 * (single-column carriers with {@link no.sikt.graphitron.rewrite.model.CallSiteExtraction.NodeIdDecodeKeys}
 * and the {@code Composite*} variants), output-side ({@link ChildField.ColumnField} /
 * {@link ChildField.CompositeColumnField} with {@link no.sikt.graphitron.rewrite.model.CallSiteCompaction.NodeIdEncodeKeys}),
 * and type-level {@link GraphitronType.NodeType} synthesis for
 * tables whose jOOQ class exposes {@code __NODE_TYPE_ID} + {@code __NODE_KEY_COLUMNS} constants
 * (synthesized route) as well as the SDL-declared {@code @node} / {@code @nodeId} directive paths.
 *
 * <p>Uses the {@code no.sikt.graphitron.rewrite.nodeidfixture} catalog — generated by
 * {@code NodeIdFixtureGenerator} in {@code graphitron-fixtures-codegen}, which extends
 * the upstream jOOQ {@code JavaGenerator} and hard-codes {@code __NODE_TYPE_ID} /
 * {@code __NODE_KEY_COLUMNS} on {@code bar} (composite key) and {@code baz} (single key). The
 * generator is a faithful model of Sikt's production {@code KjerneJooqGenerator}, so the
 * classifier is tested against real generator output rather than a hand-edited approximation.
 * <ul>
 *   <li>{@code bar} — composite-key NodeType; {@code __NODE_TYPE_ID = "Bar"},
 *       {@code __NODE_KEY_COLUMNS = { BAR.ID_1, BAR.ID_2 }}. FK {@code bar.id_1 -> baz.id}
 *       supports composite-key reference tests.</li>
 *   <li>{@code baz} — single-key NodeType; reference target for {@code bar}.</li>
 *   <li>{@code qux} — plain table; no metadata. Negative-case fixture.</li>
 *   <li>{@code parent_node} — single-key NodeType keyed on {@code PK_ID}, with a separate
 *       {@code ALT_KEY} unique column targeted by {@code child_ref.parent_alt_key}'s FK.
 *       The FK target ({@code alt_key}) does not positionally match the NodeType's keyColumn
 *       ({@code pk_id}), forcing the rooted-at-parent JOIN-with-projection path.</li>
 *   <li>{@code child_ref} — plain table; FK {@code parent_alt_key -> parent_node.alt_key} is
 *       the rooted-at-parent fixture's drive surface.</li>
 * </ul>
 */
@PipelineTier
class NodeIdPipelineTest {

    private static final String FIXTURE_JOOQ_PACKAGE = "no.sikt.graphitron.rewrite.nodeidfixture";
    private static final RewriteContext FIXTURE_CTX = new RewriteContext(
        List.of(), Path.of(""), Path.of(""),
        DEFAULT_OUTPUT_PACKAGE, FIXTURE_JOOQ_PACKAGE,
        Map.of()
    );

    // ===== Type-level NodeType synthesis =====

    enum TypeCase {
        METADATA_ONLY_NO_PROMOTION(
            "`@table` on a metadata-carrying table without `implements Node @node` stays a TableType "
                + "(NodeType promotion is opt-in; auto-promotion previously collided typeIds across "
                + "tables that shared `__NODE_TYPE_ID`)",
            """
            type Foo @table(name: "bar") { name: String }
            type Query { foo: Foo }
            """,
            schema -> assertThat(schema.type("Foo")).isInstanceOf(GraphitronType.TableType.class)),

        NODE_AND_METADATA_AGREE(
            "`@node(typeId:, keyColumns:)` matching metadata exactly → NodeType (accepted)",
            """
            type Foo implements Node @table(name: "bar") @node(typeId: "Bar", keyColumns: ["id_1", "id_2"]) { id: ID! name: String }
            type Query { foo: Foo }
            """,
            schema -> {
                var t = (GraphitronType.NodeType) schema.type("Foo");
                assertThat(t.typeId()).isEqualTo("Bar");
                assertThat(t.nodeKeyColumns()).extracting(ColumnRef::sqlName)
                    .containsExactly("id_1", "id_2");
            }),

        NODE_WITHOUT_ARGS_DELEGATES_TO_METADATA(
            "`@node` with neither `typeId` nor `keyColumns` delegates to metadata on both axes",
            """
            type Foo implements Node @table(name: "bar") @node { id: ID! name: String }
            type Query { foo: Foo }
            """,
            schema -> {
                var t = (GraphitronType.NodeType) schema.type("Foo");
                assertThat(t.typeId()).isEqualTo("Bar");
                assertThat(t.nodeKeyColumns()).extracting(ColumnRef::sqlName)
                    .containsExactly("id_1", "id_2");
            }),

        TYPE_ID_DISAGREES_SDL_WINS(
            "`@node(typeId: \"Foo\")` on a metadata-carrying table → NodeType with SDL typeId (durability: SDL author pins wire format)",
            """
            type Foo implements Node @table(name: "bar") @node(typeId: "Foo", keyColumns: ["id_1", "id_2"]) { id: ID! name: String }
            type Query { foo: Foo }
            """,
            schema -> {
                var t = (GraphitronType.NodeType) schema.type("Foo");
                assertThat(t.typeId()).isEqualTo("Foo");
                assertThat(t.nodeKeyColumns()).extracting(ColumnRef::sqlName)
                    .containsExactly("id_1", "id_2");
            }),

        KEY_COLUMNS_ORDER_ONLY_DIFFERS_SDL_WINS(
            "`@node(keyColumns: [...])` with same set but different order from metadata → NodeType with SDL order (WARN logged but not blocking)",
            """
            type Foo implements Node @table(name: "bar") @node(typeId: "Bar", keyColumns: ["id_2", "id_1"]) { id: ID! name: String }
            type Query { foo: Foo }
            """,
            schema -> {
                var t = (GraphitronType.NodeType) schema.type("Foo");
                assertThat(t.typeId()).isEqualTo("Bar");
                assertThat(t.nodeKeyColumns()).extracting(ColumnRef::sqlName)
                    .containsExactly("id_2", "id_1");
            }),

        KEY_COLUMNS_SET_DIFFERS_HARD_ERROR(
            "`@node(keyColumns: [...])` with different *set* from metadata → UnclassifiedType (one side wrong about the schema)",
            """
            type Foo implements Node @table(name: "bar") @node(keyColumns: ["id_1"]) { id: ID! name: String }
            type Query { foo: Foo }
            """,
            schema -> {
                var t = (GraphitronType.UnclassifiedType) schema.type("Foo");
                assertThat(t.reason())
                    .contains("column sets are different")
                    .contains("[\"id_1\"]")
                    .contains("[\"id_1\", \"id_2\"]");
            }),

        TYPE_ID_ONLY_DISAGREES_KEY_COLUMNS_OMITTED(
            "`@node(typeId: \"Foo\")` without keyColumns → NodeType (SDL typeId wins silently; keyColumns fall through to metadata)",
            """
            type Foo implements Node @table(name: "bar") @node(typeId: "Foo") { id: ID! name: String }
            type Query { foo: Foo }
            """,
            schema -> {
                var t = (GraphitronType.NodeType) schema.type("Foo");
                assertThat(t.typeId()).isEqualTo("Foo");
                assertThat(t.nodeKeyColumns()).extracting(ColumnRef::sqlName)
                    .containsExactly("id_1", "id_2");
            }),

        NODE_WITHOUT_IMPLEMENTS_NODE(
            "`@node` on a type that does not `implements Node` → UnclassifiedType (schema contract violation)",
            """
            type Foo @table(name: "bar") @node { name: String }
            type Query { foo: Foo }
            """,
            schema -> {
                var t = (GraphitronType.UnclassifiedType) schema.type("Foo");
                assertThat(t.reason()).contains("implements Node");
            }),

        NO_METADATA_NO_NODE(
            "`@table` on a table without metadata → TableType (no synthesis)",
            """
            type Foo @table(name: "qux") { name: String }
            type Query { foo: Foo }
            """,
            schema -> assertThat(schema.type("Foo")).isInstanceOf(GraphitronType.TableType.class)),

        NODE_ONLY_NO_METADATA_TYPEID_DECLARED(
            "`@node(typeId:)` without keyColumns and no metadata → NodeType with SDL typeId and PK fallback (R3)",
            """
            type Foo implements Node @table(name: "qux") @node(typeId: "Foo") { id: ID! name: String }
            type Query { foo: Foo }
            """,
            schema -> {
                var t = (GraphitronType.NodeType) schema.type("Foo");
                assertThat(t.typeId()).isEqualTo("Foo");
                assertThat(t.nodeKeyColumns()).extracting(ColumnRef::sqlName)
                    .containsExactly("name");
            }),

        NODE_ONLY_NO_METADATA_DEFAULTS_FROM_SDL(
            "`@node` with no args and no metadata → NodeType with typeId = SDL type name and PK fallback (R3)",
            """
            type Foo implements Node @table(name: "qux") @node { id: ID! name: String }
            type Query { foo: Foo }
            """,
            schema -> {
                var t = (GraphitronType.NodeType) schema.type("Foo");
                assertThat(t.typeId()).isEqualTo("Foo");
                assertThat(t.nodeKeyColumns()).extracting(ColumnRef::sqlName)
                    .containsExactly("name");
            }),

        TYPE_ID_COLLISION_DEMOTES_BOTH(
            "two NodeTypes with the same typeId → both demoted to UnclassifiedType (R4a registry uniqueness)",
            """
            type Foo implements Node @table(name: "bar") @node(typeId: "Shared") { id: ID! name: String }
            type Zed implements Node @table(name: "qux") @node(typeId: "Shared") { id: ID! name: String }
            type Query { foo: Foo zed: Zed }
            """,
            schema -> {
                assertThat(schema.type("Foo")).isInstanceOf(GraphitronType.UnclassifiedType.class);
                assertThat(schema.type("Zed")).isInstanceOf(GraphitronType.UnclassifiedType.class);
                var fooReason = ((GraphitronType.UnclassifiedType) schema.type("Foo")).reason();
                assertThat(fooReason)
                    .contains("typeId 'Shared'")
                    .contains("Foo, Zed")
                    .contains("nondeterministic");
            }),

        METADATA_ONLY_TYPES_DO_NOT_COLLIDE(
            "two `@table`-only types backed by metadata-carrying tables stay TableType — no NodeType "
                + "promotion, so no typeId collision even when the tables share `__NODE_TYPE_ID`-style "
                + "metadata. Regression for the sis bug where ~200 `@table` event types were silently "
                + "promoted and then mass-demoted via the registry-uniqueness check.",
            """
            type Foo @table(name: "bar") { name: String }
            type Zed @table(name: "baz") { name: String }
            type Query { foo: Foo zed: Zed }
            """,
            schema -> {
                assertThat(schema.type("Foo")).isInstanceOf(GraphitronType.TableType.class);
                assertThat(schema.type("Zed")).isInstanceOf(GraphitronType.TableType.class);
            });

        final String sdl;
        final Consumer<GraphitronSchema> assertions;
        TypeCase(String description, String sdl, Consumer<GraphitronSchema> assertions) {
            this.sdl = sdl;
            this.assertions = assertions;
        }
        @Override public String toString() { return name().toLowerCase().replace('_', ' '); }
    }

    @ParameterizedTest(name = "{0}")
    @EnumSource(TypeCase.class)
    void typeLevelNodeSynthesis(TypeCase tc) {
        tc.assertions.accept(TestSchemaHelper.buildSchema(tc.sdl, FIXTURE_CTX));
    }

    @org.junit.jupiter.api.Test
    void nodeTypeWireFormat_independentOfSdlTypeName() {
        // Opacity invariant: an opaque ID encodes against (typeId, keyColumns), neither of
        // which is the SDL type name. Renaming the SDL type while pinning @node(typeId:) and
        // pointing at the same table must produce a structurally identical NodeType — the
        // wire-format carrier the encoder and dispatcher consult. If a refactor ever leaked
        // the SDL type name into typeId or keyColumns, every ID issued before the rename
        // would silently stop resolving.
        String sdlOriginal = """
            type Foo implements Node @table(name: "bar") @node(typeId: "FrozenWire") { id: ID! name: String }
            type Query { foo: Foo }
            """;
        String sdlRenamed = """
            type RenamedFoo implements Node @table(name: "bar") @node(typeId: "FrozenWire") { id: ID! name: String }
            type Query { foo: RenamedFoo }
            """;
        var schemaA = TestSchemaHelper.buildSchema(sdlOriginal, FIXTURE_CTX);
        var schemaB = TestSchemaHelper.buildSchema(sdlRenamed, FIXTURE_CTX);

        var ntA = (GraphitronType.NodeType) schemaA.type("Foo");
        var ntB = (GraphitronType.NodeType) schemaB.type("RenamedFoo");

        assertThat(ntA.typeId()).isEqualTo("FrozenWire");
        assertThat(ntB.typeId()).isEqualTo(ntA.typeId());
        assertThat(ntB.nodeKeyColumns()).extracting(ColumnRef::sqlName)
            .isEqualTo(ntA.nodeKeyColumns().stream().map(ColumnRef::sqlName).toList());
    }

    // ===== Input side =====

    enum InputCase {
        IMPLICIT_ID(
            "input `id: ID!` on a composite-PK node-type table → CompositeColumnField with NodeIdDecodeKeys.SkipMismatchedElement",
            """
            input Foo @table(name: "bar") { id: ID! }
            type Query { x: String }
            """,
            schema -> {
                var t = (GraphitronType.TableInputType) schema.type("Foo");
                var f = (InputField.CompositeColumnField) t.inputFields().get(0);
                assertThat(f.columns()).extracting(ColumnRef::sqlName)
                    .containsExactly("id_1", "id_2");
                assertThat(f.extraction())
                    .isInstanceOf(no.sikt.graphitron.rewrite.model.CallSiteExtraction.SkipMismatchedElement.class);
                assertThat(f.extraction().decodeMethod().methodName()).isEqualTo("decodeBar");
            }),

        EXPLICIT_PERSON_ID(
            "input `personId: ID! @field(name: \"PERSON_ID\")` on a composite-PK node-type table → CompositeColumnField with NodeIdDecodeKeys (PERSON_ID has no column, nodeId metadata wins)",
            """
            input Foo @table(name: "bar") { personId: ID! @field(name: "PERSON_ID") }
            type Query { x: String }
            """,
            schema -> {
                var t = (GraphitronType.TableInputType) schema.type("Foo");
                var f = (InputField.CompositeColumnField) t.inputFields().get(0);
                assertThat(f.columns()).extracting(ColumnRef::sqlName)
                    .containsExactly("id_1", "id_2");
                assertThat(f.extraction())
                    .isInstanceOf(no.sikt.graphitron.rewrite.model.CallSiteExtraction.SkipMismatchedElement.class);
            }),

        EXPLICIT_NODE_ID_DIRECTIVE(
            "R131 four-corners: singular `id: ID! @nodeId` on a @table input whose table is the"
                + " same as the inferred NodeType's table, composite-PK → CompositeColumnField"
                + " (same-table filter against the parent's own PK columns; not a reference)",
            """
            type Bar @table(name: "bar") @node { id: ID! @nodeId }
            input Foo @table(name: "bar") { id: ID! @nodeId }
            type Query { x: String }
            """,
            schema -> {
                var t = (GraphitronType.TableInputType) schema.type("Foo");
                var f = (InputField.CompositeColumnField) t.inputFields().get(0);
                assertThat(f.list()).isFalse();
                assertThat(f.columns()).extracting(ColumnRef::sqlName)
                    .containsExactly("id_1", "id_2");
                assertThat(f.extraction())
                    .isInstanceOf(no.sikt.graphitron.rewrite.model.CallSiteExtraction.SkipMismatchedElement.class);
                assertThat(f.extraction().decodeMethod().methodName()).isEqualTo("decodeBar");
            }),

        EXPLICIT_NODE_ID_DIRECTIVE_SINGLE_PK(
            "R131 four-corners: singular `id: ID! @nodeId(typeName: \"Baz\")` on a @table input"
                + " whose table is the same as Baz's table (baz, single-PK) → ColumnField"
                + " (same-table arity-1 case)",
            """
            type Baz @table(name: "baz") @node { id: ID! @nodeId }
            input BazSelector @table(name: "baz") { id: ID! @nodeId(typeName: "Baz") }
            type Query { x: String }
            """,
            schema -> {
                var t = (GraphitronType.TableInputType) schema.type("BazSelector");
                var f = (InputField.ColumnField) t.inputFields().get(0);
                assertThat(f.list()).isFalse();
                assertThat(f.column().sqlName()).isEqualTo("id");
                var skip = (no.sikt.graphitron.rewrite.model.CallSiteExtraction.SkipMismatchedElement) f.extraction();
                assertThat(skip.decodeMethod().methodName()).isEqualTo("decodeBaz");
            }),

        BARE_NODE_ID_NO_OBJECT_TYPE(
            "input `id: ID! @nodeId` on a @table whose table has no matching object type → friendly error",
            """
            input Foo @table(name: "bar") { id: ID! @nodeId }
            type Query { x: String }
            """,
            schema -> {
                var t = (GraphitronType.UnclassifiedType) schema.type("Foo");
                assertThat(t.reason())
                    .contains("@nodeId without typeName: cannot infer node type")
                    .contains("no @table-annotated object type maps to table 'bar'")
                    .contains("Add typeName: explicitly");
            }),

        BARE_NODE_ID_AMBIGUOUS_OBJECT_TYPES(
            "input `id: ID! @nodeId` on a @table shared by two object types → friendly ambiguity error",
            """
            type BarA @table(name: "bar") @node { id: ID! @nodeId }
            type BarB @table(name: "bar") @node { id: ID! @nodeId }
            input Foo @table(name: "bar") { id: ID! @nodeId }
            type Query { a: BarA b: BarB }
            """,
            schema -> {
                var t = (GraphitronType.UnclassifiedType) schema.type("Foo");
                assertThat(t.reason())
                    .contains("@nodeId without typeName: is ambiguous")
                    .contains("multiple object types map to table 'bar'")
                    .contains("BarA")
                    .contains("BarB")
                    .contains("Specify typeName: explicitly");
            }),

        ACCESSOR_MISSING(
            "plain ID field on a table without node-id metadata → TableInputType fails, type becomes UnclassifiedType",
            """
            input Foo @table(name: "qux") { id: ID! }
            type Query { x: String }
            """,
            schema -> assertThat(schema.type("Foo")).isInstanceOf(GraphitronType.UnclassifiedType.class)),

        LIST_VARIANT(
            "list ID input skips the node-id check (list gate) → UnclassifiedType",
            """
            input Foo @table(name: "bar") { id: [ID!]! }
            type Query { x: String }
            """,
            schema -> assertThat(schema.type("Foo")).isInstanceOf(GraphitronType.UnclassifiedType.class));

        final String sdl;
        final Consumer<GraphitronSchema> assertions;
        InputCase(String description, String sdl, Consumer<GraphitronSchema> assertions) {
            this.sdl = sdl;
            this.assertions = assertions;
        }
        @Override public String toString() { return name().toLowerCase().replace('_', ' '); }
    }

    @ParameterizedTest(name = "{0}")
    @EnumSource(InputCase.class)
    void inputNodeIdClassification(InputCase tc) {
        tc.assertions.accept(TestSchemaHelper.buildSchema(tc.sdl, FIXTURE_CTX));
    }

    // ===== Input reference side =====

    enum InputReferenceCase {
        REFERENCE_TO_NODE_TYPE(
            "R131 four-corners: singular `relatedId: ID! @nodeId(typeName: 'Baz')` on bar table"
                + " (FK bar.id_1 -> baz.id, single-PK target) → ColumnReferenceField with"
                + " NodeIdDecodeKeys.SkipMismatchedElement",
            """
            type Baz @table(name: "baz") { id: ID! }
            input Foo @table(name: "bar") { relatedId: ID! @nodeId(typeName: "Baz") }
            type Query { x: String }
            """,
            schema -> {
                var t = (GraphitronType.TableInputType) schema.type("Foo");
                var f = (InputField.ColumnReferenceField) t.inputFields().get(0);
                assertThat(f.typeName()).isEqualTo("ID");
                assertThat(f.list()).isFalse();
                assertThat(f.column().sqlName()).isEqualTo("id");
                assertThat(f.joinPath()).hasSize(1);
                assertThat(f.extraction())
                    .isInstanceOf(no.sikt.graphitron.rewrite.model.CallSiteExtraction.SkipMismatchedElement.class);
                assertThat(((no.sikt.graphitron.rewrite.model.CallSiteExtraction.NodeIdDecodeKeys) f.extraction())
                    .decodeMethod().methodName()).isEqualTo("decodeBaz");
            }),

        REFERENCE_TO_COMPOSITE_PK_NODE_TYPE(
            "R131 four-corners: singular `parentId: ID! @nodeId(typeName: 'LevelA')` on"
                + " level_b table (FK level_b.(k1,k2) -> level_a.(k1,k2), composite-PK target) →"
                + " CompositeColumnReferenceField with joinPath length 1 and the lifted source"
                + " columns positionally aligned with the NodeType key",
            """
            type LevelA implements Node @table(name: "level_a") @node(typeId: "LevelA", keyColumns: ["k1", "k2"]) { id: ID! @nodeId }
            input LevelBFilter @table(name: "level_b") { parentId: ID! @nodeId(typeName: "LevelA") }
            type Query { x: String }
            """,
            schema -> {
                var t = (GraphitronType.TableInputType) schema.type("LevelBFilter");
                var f = (InputField.CompositeColumnReferenceField) t.inputFields().get(0);
                assertThat(f.list()).isFalse();
                assertThat(f.columns()).extracting(ColumnRef::sqlName)
                    .containsExactly("k1", "k2");
                assertThat(f.joinPath()).hasSize(1);
                assertThat(f.liftedSourceColumns()).extracting(ColumnRef::sqlName)
                    .containsExactly("k1", "k2");
                assertThat(f.extraction())
                    .isInstanceOf(no.sikt.graphitron.rewrite.model.CallSiteExtraction.SkipMismatchedElement.class);
                assertThat(f.extraction().decodeMethod().methodName()).isEqualTo("decodeLevelA");
            }),

        TARGET_NOT_A_NODE_TYPE(
            "input `relatedId: ID! @nodeId(typeName: 'Qux')` where Qux is not a NodeType → UnclassifiedType",
            """
            type Qux @table(name: "qux") { name: String }
            input Foo @table(name: "bar") { relatedId: ID! @nodeId(typeName: "Qux") }
            type Query { x: String }
            """,
            schema -> assertThat(schema.type("Foo")).isInstanceOf(GraphitronType.UnclassifiedType.class)),

        LIST_VARIANT(
            "list `[ID!]!` with @nodeId(typeName:) and no FK from source to target → UnclassifiedType (no FK from 'qux' to 'baz')",
            """
            type Baz @table(name: "baz") { id: ID! }
            input Foo @table(name: "qux") { relatedId: [ID!]! @nodeId(typeName: "Baz") }
            type Query { x: String }
            """,
            schema -> assertThat(schema.type("Foo")).isInstanceOf(GraphitronType.UnclassifiedType.class)),

        NO_FK_PATH(
            "input `relatedId: ID! @nodeId(typeName: 'Baz')` where no FK from qux to baz → UnclassifiedType (path resolver rejects)",
            """
            type Baz @table(name: "baz") { id: ID! }
            input Foo @table(name: "qux") { relatedId: ID! @nodeId(typeName: "Baz") }
            type Query { x: String }
            """,
            schema -> assertThat(schema.type("Foo")).isInstanceOf(GraphitronType.UnclassifiedType.class)),

        NODE_TARGET_NO_METADATA_PK_FALLBACK(
            "input `id: ID! @nodeId(typeName: 'Qux')` where Qux has @node but its table has no"
                + " NodeId metadata → ColumnField via catalog PK fallback (post-R131: same-table"
                + " classification; before R131 this produced a ColumnReferenceField with empty"
                + " joinPath, which was a giveaway of the same-table case being mis-classified"
                + " as a reference)",
            """
            type Qux implements Node @table(name: "qux") @node { id: ID! name: String }
            input Foo @table(name: "qux") { id: ID! @nodeId(typeName: "Qux") }
            type Query { x: String }
            """,
            schema -> {
                var t = (GraphitronType.TableInputType) schema.type("Foo");
                var f = (InputField.ColumnField) t.inputFields().get(0);
                assertThat(f.list()).isFalse();
                assertThat(f.column().sqlName()).isEqualTo("name");
                assertThat(f.extraction())
                    .isInstanceOf(no.sikt.graphitron.rewrite.model.CallSiteExtraction.SkipMismatchedElement.class);
            });

        final String sdl;
        final Consumer<GraphitronSchema> assertions;
        InputReferenceCase(String description, String sdl, Consumer<GraphitronSchema> assertions) {
            this.sdl = sdl;
            this.assertions = assertions;
        }
        @Override public String toString() { return name().toLowerCase().replace('_', ' '); }
    }

    @ParameterizedTest(name = "{0}")
    @EnumSource(InputReferenceCase.class)
    void inputNodeIdReferenceClassification(InputReferenceCase tc) {
        tc.assertions.accept(TestSchemaHelper.buildSchema(tc.sdl, FIXTURE_CTX));
    }

    // ===== FK-qualifier synthesis shim =====

    /**
     * Synthesis-shim cases that route the FK-qualifier hit onto
     * {@link InputField.ColumnReferenceField} (or
     * {@link InputField.CompositeColumnReferenceField} for composite-PK FK targets) carrying
     * {@link CallSiteExtraction.NodeIdDecodeKeys.SkipMismatchedElement} plus the resolved FK
     * joinPath. All use the nodeidfixture catalog so that
     * {@code catalog.nodeIdMetadata("baz")} returns present (the shim's gate condition).
     * {@code bar} carries FK {@code bar_id_1_fkey} to {@code baz}; the qualifier map keys for
     * that FK are {@code "1_baz_id"} (raw), {@code "1bazid"} (camelCase), and
     * {@code "1bazids"} (plural camelCase), all used via explicit {@code @field(name:)} since
     * the qualifier starts with a digit and therefore cannot appear as a bare GraphQL field
     * name.
     */
    enum InputIdReferenceCase {
        SHIM_RAW_QUALIFIER_KEY(
            "@field(name: \"1_baz_id\") hits raw-qualifier map key → ColumnReferenceField with NodeIdDecodeKeys",
            """
            type Baz @table(name: "baz") { id: ID! }
            input Foo @table(name: "bar") {
              barRef: [ID!] @field(name: "1_baz_id")
            }
            type Query { x: String }
            """,
            schema -> {
                var tit = (GraphitronType.TableInputType) schema.type("Foo");
                var f = (InputField.ColumnReferenceField) tit.inputFields().get(0);
                assertThat(f.list()).isTrue();
                assertThat(f.column().sqlName()).isEqualTo("id");
                assertThat(f.extraction()).isInstanceOf(CallSiteExtraction.SkipMismatchedElement.class);
                assertThat(f.joinPath()).hasSize(1);
            }),

        SHIM_PLURAL_CAMEL_KEY(
            "@field(name: \"1bazids\") hits plural camelCase map key → ColumnReferenceField with NodeIdDecodeKeys",
            """
            type Baz @table(name: "baz") { id: ID! }
            input Foo @table(name: "bar") {
              barRef: [ID!] @field(name: "1bazids")
            }
            type Query { x: String }
            """,
            schema -> {
                var tit = (GraphitronType.TableInputType) schema.type("Foo");
                var f = (InputField.ColumnReferenceField) tit.inputFields().get(0);
                assertThat(f.list()).isTrue();
                assertThat(f.extraction()).isInstanceOf(CallSiteExtraction.SkipMismatchedElement.class);
            }),

        SHIM_SINGULAR_CAMEL_KEY(
            "scalar ID @field(name: \"1bazid\") hits singular camelCase map key → ColumnReferenceField with NodeIdDecodeKeys (list=false)",
            """
            type Baz @table(name: "baz") { id: ID! }
            input Foo @table(name: "bar") {
              barRef: ID @field(name: "1bazid")
            }
            type Query { x: String }
            """,
            schema -> {
                var tit = (GraphitronType.TableInputType) schema.type("Foo");
                var f = (InputField.ColumnReferenceField) tit.inputFields().get(0);
                assertThat(f.list()).isFalse();
                assertThat(f.extraction()).isInstanceOf(CallSiteExtraction.SkipMismatchedElement.class);
            }),

        SHIM_BARE_ID_FALLS_THROUGH(
            "bare id: ID on a KjerneJooqGenerator composite-PK table — qualifier map miss → falls through to CompositeColumnField with NodeIdDecodeKeys",
            """
            input Foo @table(name: "bar") {
              id: ID
            }
            type Query { x: String }
            """,
            schema -> {
                var tit = (GraphitronType.TableInputType) schema.type("Foo");
                assertThat(tit.inputFields().get(0)).isInstanceOf(InputField.CompositeColumnField.class);
            });

        final String sdl;
        final Consumer<GraphitronSchema> assertions;
        InputIdReferenceCase(String description, String sdl, Consumer<GraphitronSchema> assertions) {
            this.sdl = sdl;
            this.assertions = assertions;
        }
        @Override public String toString() { return name().toLowerCase().replace('_', ' '); }
    }

    @ParameterizedTest(name = "{0}")
    @EnumSource(InputIdReferenceCase.class)
    void inputIdReferenceShimClassification(InputIdReferenceCase tc) {
        tc.assertions.accept(TestSchemaHelper.buildSchema(tc.sdl, FIXTURE_CTX));
    }

    // ===== Same-table @nodeId filter =====

    /**
     * Same-table {@code [ID!] @nodeId(typeName: T)} where T maps to the input's own table.
     * Semantics: filter rows whose composite primary key matches one of the decoded node IDs;
     * a primary-key IN predicate, not a FK join. The classifier short-circuits before
     * {@code findUniqueFkToTable(t, t)} (which would always miss) and emits
     * {@link InputField.ColumnField} (arity-1) or {@link InputField.CompositeColumnField}
     * (arity &gt; 1) carrying {@link CallSiteExtraction.NodeIdDecodeKeys.SkipMismatchedElement}.
     */
    enum InputSameTableNodeIdCase {
        SAME_TABLE_COMPOSITE_PK(
            "input `[ID!] @nodeId(typeName: \"Bar\")` on a `bar`-bound input → CompositeColumnField "
                + "with NodeIdDecodeKeys over composite PK columns",
            """
            type Bar implements Node @table(name: "bar") @node { id: ID! }
            input BarFilterInput @table(name: "bar") {
              ids: [ID!] @nodeId(typeName: "Bar")
            }
            type Query { x: String }
            """,
            schema -> {
                var tit = (GraphitronType.TableInputType) schema.type("BarFilterInput");
                var f = (InputField.CompositeColumnField) tit.inputFields().stream()
                    .filter(InputField.CompositeColumnField.class::isInstance).findFirst().orElseThrow();
                assertThat(f.list()).isTrue();
                assertThat(f.columns()).extracting(ColumnRef::sqlName)
                    .containsExactly("id_1", "id_2");
                assertThat(f.extraction())
                    .isInstanceOf(CallSiteExtraction.SkipMismatchedElement.class);
                var skip = (CallSiteExtraction.SkipMismatchedElement) f.extraction();
                assertThat(skip.decodeMethod().methodName()).isEqualTo("decodeBar");
            }),

        SAME_TABLE_SINGLE_PK(
            "single-PK same-table case → ColumnField with NodeIdDecodeKeys over the one key column",
            """
            type Baz implements Node @table(name: "baz") @node { id: ID! }
            input BazFilterInput @table(name: "baz") {
              ids: [ID!] @nodeId(typeName: "Baz")
            }
            type Query { x: String }
            """,
            schema -> {
                var tit = (GraphitronType.TableInputType) schema.type("BazFilterInput");
                var f = (InputField.ColumnField) tit.inputFields().stream()
                    .filter(InputField.ColumnField.class::isInstance).findFirst().orElseThrow();
                assertThat(f.list()).isTrue();
                assertThat(f.column().sqlName()).isEqualTo("id");
                assertThat(f.extraction())
                    .isInstanceOf(CallSiteExtraction.SkipMismatchedElement.class);
                var skip = (CallSiteExtraction.SkipMismatchedElement) f.extraction();
                assertThat(skip.decodeMethod().methodName()).isEqualTo("decodeBaz");
            }),

        SAME_TABLE_TARGET_NOT_NODE(
            "same-table reference where target table has no @node metadata → UnclassifiedType "
                + "(no PK columns to encode)",
            """
            type Qux @table(name: "qux") { name: String }
            input QuxFilterInput @table(name: "qux") {
              ids: [ID!] @nodeId(typeName: "Qux")
            }
            type Query { x: String }
            """,
            schema -> assertThat(schema.type("QuxFilterInput"))
                .isInstanceOf(GraphitronType.UnclassifiedType.class)),

        BARE_LIST_NODE_ID_INFERS_TYPE_NAME(
            "bare `[ID!] @nodeId` infers typeName from the unique @table-matching object type → "
                + "CompositeColumnField (same as explicit typeName)",
            """
            type Bar implements Node @table(name: "bar") @node { id: ID! }
            input BarFilterInput @table(name: "bar") {
              ids: [ID!] @nodeId
            }
            type Query { x: String }
            """,
            schema -> {
                var tit = (GraphitronType.TableInputType) schema.type("BarFilterInput");
                var f = (InputField.CompositeColumnField) tit.inputFields().stream()
                    .filter(InputField.CompositeColumnField.class::isInstance).findFirst().orElseThrow();
                assertThat(f.list()).isTrue();
                assertThat(f.columns()).extracting(ColumnRef::sqlName)
                    .containsExactly("id_1", "id_2");
                assertThat(f.extraction())
                    .isInstanceOf(CallSiteExtraction.SkipMismatchedElement.class);
            }),

        BARE_LIST_NODE_ID_NO_OBJECT_TYPE(
            "bare `[ID!] @nodeId` with no @table-matching object type → friendly inference error",
            """
            input BarFilterInput @table(name: "bar") {
              ids: [ID!] @nodeId
            }
            type Query { x: String }
            """,
            schema -> {
                var t = (GraphitronType.UnclassifiedType) schema.type("BarFilterInput");
                assertThat(t.reason())
                    .contains("@nodeId without typeName: cannot infer node type")
                    .contains("no @table-annotated object type maps to table 'bar'");
            }),

        BARE_LIST_NODE_ID_AMBIGUOUS(
            "bare `[ID!] @nodeId` with two @table-matching object types → friendly ambiguity error",
            """
            type BarA @table(name: "bar") @node { id: ID! }
            type BarB @table(name: "bar") @node { id: ID! }
            input BarFilterInput @table(name: "bar") {
              ids: [ID!] @nodeId
            }
            type Query { a: BarA b: BarB }
            """,
            schema -> {
                var t = (GraphitronType.UnclassifiedType) schema.type("BarFilterInput");
                assertThat(t.reason())
                    .contains("@nodeId without typeName: is ambiguous")
                    .contains("BarA")
                    .contains("BarB");
            });

        final String sdl;
        final Consumer<GraphitronSchema> assertions;
        InputSameTableNodeIdCase(String description, String sdl, Consumer<GraphitronSchema> assertions) {
            this.sdl = sdl;
            this.assertions = assertions;
        }
        @Override public String toString() { return name().toLowerCase().replace('_', ' '); }
    }

    @ParameterizedTest(name = "{0}")
    @EnumSource(InputSameTableNodeIdCase.class)
    void inputSameTableNodeIdClassification(InputSameTableNodeIdCase tc) {
        tc.assertions.accept(TestSchemaHelper.buildSchema(tc.sdl, FIXTURE_CTX));
    }

    // ===== Output side =====

    enum OutputCase {
        IMPLICIT_ID(
            "output `id: ID!` on a `implements Node @node` parent backed by a metadata-carrying "
                + "table → CompositeColumnField with NodeIdEncodeKeys (composite-PK Bar uses 2 columns)",
            """
            type Foo implements Node @table(name: "bar") @node { id: ID! }
            type Query { foo: Foo }
            """,
            schema -> {
                assertThat(schema.type("Foo")).isInstanceOf(GraphitronType.NodeType.class);
                var f = (ChildField.CompositeColumnField) schema.field("Foo", "id");
                assertThat(f.columns()).extracting(ColumnRef::sqlName)
                    .containsExactly("id_1", "id_2");
                assertThat(f.compaction().encodeMethod().methodName()).isEqualTo("encodeFoo");
            }),

        ACCESSOR_MISSING(
            "column absent AND no metadata → UnclassifiedField, parent stays TableType",
            """
            type Foo @table(name: "qux") { id: ID! }
            type Query { foo: Foo }
            """,
            schema -> {
                assertThat(schema.type("Foo")).isInstanceOf(GraphitronType.TableType.class);
                assertThat(schema.field("Foo", "id"))
                    .isInstanceOf(GraphitronField.UnclassifiedField.class);
            }),

        NODE_ID_DIRECTIVE_ON_NODE_TYPE(
            "`id: ID! @nodeId` on a `implements Node @node` parent → CompositeColumnField via the "
                + "@nodeId guard (canonical opt-in form; no synthesis from `@table` alone)",
            """
            type Foo implements Node @table(name: "bar") @node { id: ID! @nodeId }
            type Query { foo: Foo }
            """,
            schema -> {
                assertThat(schema.type("Foo")).isInstanceOf(GraphitronType.NodeType.class);
                var f = (ChildField.CompositeColumnField) schema.field("Foo", "id");
                assertThat(f.columns()).extracting(ColumnRef::sqlName)
                    .containsExactly("id_1", "id_2");
                assertThat(f.compaction().encodeMethod().methodName()).isEqualTo("encodeFoo");
            });

        final String sdl;
        final Consumer<GraphitronSchema> assertions;
        OutputCase(String description, String sdl, Consumer<GraphitronSchema> assertions) {
            this.sdl = sdl;
            this.assertions = assertions;
        }
        @Override public String toString() { return name().toLowerCase().replace('_', ' '); }
    }

    @ParameterizedTest(name = "{0}")
    @EnumSource(OutputCase.class)
    void outputNodeIdClassification(OutputCase tc) {
        tc.assertions.accept(TestSchemaHelper.buildSchema(tc.sdl, FIXTURE_CTX));
    }

    // ===== Lookup arg side (composite-PK NodeId @lookupKey) =====

    enum LookupKeyCase {
        SCALAR_NODEID_LOOKUP_COMPOSITE_PK(
            "scalar `id: ID @lookupKey` arg on a composite-PK NodeType-backed lookup → "
                + "CompositeColumnArg(ThrowOnMismatch) → projectForLookup lifts to DecodedRecord "
                + "with positional RecordBindings over the composite key columns",
            """
            type Bar implements Node @table(name: "bar") @node { id: ID! @nodeId name: String }
            type Query { barById(id: ID @lookupKey): Bar }
            """,
            schema -> {
                var f = (no.sikt.graphitron.rewrite.model.QueryField.QueryLookupTableField)
                    schema.field("Query", "barById");
                var cm = (no.sikt.graphitron.rewrite.model.LookupMapping.ColumnMapping) f.lookupMapping();
                assertThat(cm.args()).hasSize(1);
                var arg = (no.sikt.graphitron.rewrite.model.LookupMapping.ColumnMapping.LookupArg.DecodedRecord)
                    cm.args().get(0);
                assertThat(arg.argName()).isEqualTo("id");
                assertThat(arg.list()).isFalse();
                assertThat(arg.extraction().decodeMethod().methodName()).isEqualTo("decodeBar");
                assertThat(arg.bindings()).hasSize(2);
                assertThat(arg.bindings()).extracting(b -> b.targetColumn().sqlName())
                    .containsExactly("id_1", "id_2");
                assertThat(arg.bindings()).extracting(no.sikt.graphitron.rewrite.model.InputColumnBinding.RecordBinding::index)
                    .containsExactly(0, 1);
            }),

        LIST_NODEID_LOOKUP_COMPOSITE_PK(
            "list `ids: [ID!] @lookupKey` arg on a composite-PK NodeType-backed lookup → "
                + "DecodedRecord with list=true; each input id decodes once per row to drive "
                + "the VALUES + JOIN row-IN shape",
            """
            type Bar implements Node @table(name: "bar") @node { id: ID! @nodeId name: String }
            type Query { barsByIds(ids: [ID!] @lookupKey): [Bar!]! }
            """,
            schema -> {
                var f = (no.sikt.graphitron.rewrite.model.QueryField.QueryLookupTableField)
                    schema.field("Query", "barsByIds");
                var cm = (no.sikt.graphitron.rewrite.model.LookupMapping.ColumnMapping) f.lookupMapping();
                var arg = (no.sikt.graphitron.rewrite.model.LookupMapping.ColumnMapping.LookupArg.DecodedRecord)
                    cm.args().get(0);
                assertThat(arg.list()).isTrue();
                assertThat(arg.bindings()).hasSize(2);
            }),

        SCALAR_NODEID_NON_LOOKUP_COMPOSITE_PK_DEFERRED(
            "scalar `id: ID @nodeId` arg without `@lookupKey` on a composite-PK NodeType is not "
                + "yet wired (mutation-key + top-level filter paths are not supported); "
                + "surfaces as UnclassifiedField at the surrounding query field",
            """
            type Bar @table(name: "bar") { id: ID! @field(name: "ID_1") }
            type Query { bar(id: ID): Bar }
            """,
            schema -> {
                var f = schema.field("Query", "bar");
                assertThat(f).isInstanceOf(no.sikt.graphitron.rewrite.model.GraphitronField.UnclassifiedField.class);
                var uf = (no.sikt.graphitron.rewrite.model.GraphitronField.UnclassifiedField) f;
                assertThat(uf.reason()).contains("composite-PK NodeType");
            });

        final String sdl;
        final Consumer<GraphitronSchema> assertions;
        LookupKeyCase(String description, String sdl, Consumer<GraphitronSchema> assertions) {
            this.sdl = sdl;
            this.assertions = assertions;
        }
        @Override public String toString() { return name().toLowerCase().replace('_', ' '); }
    }

    @ParameterizedTest(name = "{0}")
    @EnumSource(LookupKeyCase.class)
    void lookupKeyClassification(LookupKeyCase tc) {
        tc.assertions.accept(TestSchemaHelper.buildSchema(tc.sdl, FIXTURE_CTX));
    }

    // ===== Rooted-at-parent single-hop reference =====
    //
    // child_ref.parent_alt_key references parent_node.alt_key (the *non-PK* unique column);
    // ParentNode's __NODE_KEY_COLUMNS pins the keyColumn to PK_ID. The FK target column does not
    // positionally match the keyColumn, so fkMirrorSourceColumns returns null and the classifier
    // routes through the rooted-at-parent JOIN-with-projection path: a ColumnReferenceField
    // whose column is the parent's keyColumn (read from the joined parent_node) and whose
    // joinPath carries the single FK hop. See lift-nodeid-out-of-model.md "Variant-by-variant
    // collapse → Single-hop emission, two shapes".

    @Test
    void rootedAtParent_nonMirrorFk_resolvesToColumnReferenceField() {
        var schema = TestSchemaHelper.buildSchema("""
            type ParentNode implements Node @table(name: "parent_node") @node {
                id: ID! @nodeId
                altKey: String! @field(name: "alt_key")
                name: String
            }
            type ChildRef @table(name: "child_ref") {
                childId: String! @field(name: "child_id")
                parentNodeId: ID @nodeId(typeName: "ParentNode")
                    @reference(path: [{key: "child_ref_parent_alt_key_fkey"}])
            }
            type Query { childRefs: [ChildRef!]! }
            """, FIXTURE_CTX);

        var f = (ChildField.ColumnReferenceField) schema.field("ChildRef", "parentNodeId");
        // Projected column is ParentNode's keyColumn (pk_id), not the FK target (alt_key);
        // emitter must read it through the joined parent_node alias.
        assertThat(f.column().sqlName()).isEqualTo("pk_id");
        // Single-hop FK chain — child_ref → parent_node — drives the JOIN-with-projection path.
        assertThat(f.joinPath()).hasSize(1);
        // NodeId encode call: per-type encoder helper resolved at classify time.
        var enc = (CallSiteCompaction.NodeIdEncodeKeys) f.compaction();
        assertThat(enc.encodeMethod().methodName()).isEqualTo("encodeParentNode");
        assertThat(enc.encodeMethod().paramSignature())
            .extracting(ColumnRef::sqlName)
            .containsExactly("pk_id");
    }

    // ===== Argument-level @nodeId =====
    //
    // Top-level argument @nodeId leaves classify into one of two shapes per NodeIdLeafResolver:
    //   - Same-table (T.table() == field.backingTable()) — lookup-by-id semantics; projects to
    //     ColumnArg/CompositeColumnArg with isLookupKey=true so LookupMappingResolver picks it
    //     up identically to @lookupKey-synthesised carriers (extraction is ThrowOnMismatch to
    //     match the existing lookup-key dispatch contract).
    //   - FK-target (T.table() reachable via single-hop FK) — filter semantics; projects to
    //     ColumnReferenceArg/CompositeColumnReferenceArg with the resolved joinPath. Today's
    //     emitter shipping subset is the simple direct-FK case (FK targetColumns positionally
    //     equal NodeType keyColumns); pathological cases are rejected at classify time with a
    //     pointed deferred-emission hint, parallel to R24's output-side JOIN-with-projection.

    enum ArgumentSameTableNodeIdCase {
        SAME_TABLE_SCALAR_SINGLE_PK(
            "R131 pin (FieldBuilder.classifyArgument, singular + same-table + single-PK): scalar"
                + " `id: ID! @nodeId(typeName: \"Baz\")` arg on a Baz-returning field → "
                + "QueryTableField with BodyParam.Eq over baz.id (R106: same-table @nodeId lifts "
                + "to filter, not lookup)",
            """
            type Baz implements Node @table(name: "baz") @node { id: ID! }
            type Query { bazById(id: ID! @nodeId(typeName: "Baz")): Baz }
            """,
            schema -> {
                var f = (no.sikt.graphitron.rewrite.model.QueryField.QueryTableField)
                    schema.field("Query", "bazById");
                var gcf = (no.sikt.graphitron.rewrite.model.GeneratedConditionFilter)
                    f.filters().stream()
                        .filter(no.sikt.graphitron.rewrite.model.GeneratedConditionFilter.class::isInstance)
                        .findFirst().orElseThrow();
                var bp = (no.sikt.graphitron.rewrite.model.BodyParam.Eq) gcf.bodyParams().stream()
                    .filter(no.sikt.graphitron.rewrite.model.BodyParam.Eq.class::isInstance)
                    .findFirst().orElseThrow();
                assertThat(bp.column().sqlName()).isEqualTo("id");
                assertThat(bp.extraction()).isInstanceOf(CallSiteExtraction.SkipMismatchedElement.class);
                var skip = (CallSiteExtraction.SkipMismatchedElement) bp.extraction();
                assertThat(skip.decodeMethod().methodName()).isEqualTo("decodeBaz");
            }),

        SAME_TABLE_SCALAR_COMPOSITE_PK(
            "R131 pin (FieldBuilder.classifyArgument, singular + same-table + composite-PK):"
                + " scalar `id: ID! @nodeId(typeName: \"Bar\")` arg on a Bar-returning field"
                + " (Bar composite-PK) → QueryTableField with BodyParam.RowEq over"
                + " bar.(id_1, id_2), confirming the same-table arm picks the column-direct"
                + " carrier rather than a reference carrier",
            """
            type Bar implements Node @table(name: "bar") @node { id: ID! }
            type Query { barById(id: ID! @nodeId(typeName: "Bar")): Bar }
            """,
            schema -> {
                var f = (no.sikt.graphitron.rewrite.model.QueryField.QueryTableField)
                    schema.field("Query", "barById");
                var gcf = (no.sikt.graphitron.rewrite.model.GeneratedConditionFilter)
                    f.filters().stream()
                        .filter(no.sikt.graphitron.rewrite.model.GeneratedConditionFilter.class::isInstance)
                        .findFirst().orElseThrow();
                var bp = (no.sikt.graphitron.rewrite.model.BodyParam.RowEq) gcf.bodyParams().stream()
                    .filter(no.sikt.graphitron.rewrite.model.BodyParam.RowEq.class::isInstance)
                    .findFirst().orElseThrow();
                assertThat(bp.columns()).extracting(ColumnRef::sqlName)
                    .containsExactly("id_1", "id_2");
                assertThat(bp.extraction()).isInstanceOf(CallSiteExtraction.SkipMismatchedElement.class);
                var skip = (CallSiteExtraction.SkipMismatchedElement) bp.extraction();
                assertThat(skip.decodeMethod().methodName()).isEqualTo("decodeBar");
            }),

        SAME_TABLE_LIST_SINGLE_PK(
            "list `ids: [ID!]! @nodeId(typeName: \"Baz\")` arg → "
                + "QueryTableField with BodyParam.In over baz.id (R106: filter lift)",
            """
            type Baz implements Node @table(name: "baz") @node { id: ID! }
            type Query { bazByIds(ids: [ID!]! @nodeId(typeName: "Baz")): [Baz!]! }
            """,
            schema -> {
                var f = (no.sikt.graphitron.rewrite.model.QueryField.QueryTableField)
                    schema.field("Query", "bazByIds");
                var gcf = (no.sikt.graphitron.rewrite.model.GeneratedConditionFilter)
                    f.filters().stream()
                        .filter(no.sikt.graphitron.rewrite.model.GeneratedConditionFilter.class::isInstance)
                        .findFirst().orElseThrow();
                var bp = (no.sikt.graphitron.rewrite.model.BodyParam.In) gcf.bodyParams().stream()
                    .filter(no.sikt.graphitron.rewrite.model.BodyParam.In.class::isInstance)
                    .findFirst().orElseThrow();
                assertThat(bp.column().sqlName()).isEqualTo("id");
            }),

        SAME_TABLE_LIST_COMPOSITE_PK(
            "list `ids: [ID!]! @nodeId(typeName: \"Bar\")` over composite-PK NodeType → "
                + "QueryTableField with BodyParam.RowIn (R106: filter lift; per-row decode preserved)",
            """
            type Bar implements Node @table(name: "bar") @node { id: ID! }
            type Query { barByIds(ids: [ID!]! @nodeId(typeName: "Bar")): [Bar!]! }
            """,
            schema -> {
                var f = (no.sikt.graphitron.rewrite.model.QueryField.QueryTableField)
                    schema.field("Query", "barByIds");
                var gcf = (no.sikt.graphitron.rewrite.model.GeneratedConditionFilter)
                    f.filters().stream()
                        .filter(no.sikt.graphitron.rewrite.model.GeneratedConditionFilter.class::isInstance)
                        .findFirst().orElseThrow();
                var bp = (no.sikt.graphitron.rewrite.model.BodyParam.RowIn) gcf.bodyParams().stream()
                    .filter(no.sikt.graphitron.rewrite.model.BodyParam.RowIn.class::isInstance)
                    .findFirst().orElseThrow();
                assertThat(bp.columns()).hasSize(2);
                assertThat(bp.extraction()).isInstanceOf(CallSiteExtraction.SkipMismatchedElement.class);
                var skip = (CallSiteExtraction.SkipMismatchedElement) bp.extraction();
                assertThat(skip.decodeMethod().methodName()).isEqualTo("decodeBar");
            }),

        BARE_NODEID_DEFAULTS_TO_BACKING_TABLE(
            "bare `ids: [ID!]! @nodeId` infers typeName from the unique @table-matching object "
                + "type backing the field's resolved table → BodyParam.RowIn identical to the "
                + "explicit-typeName case (R106: filter lift)",
            """
            type Bar implements Node @table(name: "bar") @node { id: ID! }
            type Query { barByIds(ids: [ID!]! @nodeId): [Bar!]! }
            """,
            schema -> {
                var f = (no.sikt.graphitron.rewrite.model.QueryField.QueryTableField)
                    schema.field("Query", "barByIds");
                var gcf = (no.sikt.graphitron.rewrite.model.GeneratedConditionFilter)
                    f.filters().stream()
                        .filter(no.sikt.graphitron.rewrite.model.GeneratedConditionFilter.class::isInstance)
                        .findFirst().orElseThrow();
                var bp = (no.sikt.graphitron.rewrite.model.BodyParam.RowIn) gcf.bodyParams().stream()
                    .filter(no.sikt.graphitron.rewrite.model.BodyParam.RowIn.class::isInstance)
                    .findFirst().orElseThrow();
                var skip = (CallSiteExtraction.SkipMismatchedElement) bp.extraction();
                assertThat(skip.decodeMethod().methodName()).isEqualTo("decodeBar");
            }),

        T_NOT_IN_SCHEMA(
            "@nodeId(typeName: \"DoesNotExist\") → UnclassifiedField (target type not in schema)",
            """
            type Baz implements Node @table(name: "baz") @node { id: ID! }
            type Query { bazById(id: ID @nodeId(typeName: "DoesNotExist")): Baz }
            """,
            schema -> {
                var f = (GraphitronField.UnclassifiedField) schema.field("Query", "bazById");
                assertThat(f.reason()).contains("@nodeId(typeName:) type 'DoesNotExist'");
            }),

        T_NOT_TABLE_ANNOTATED(
            "@nodeId(typeName: T) where T is not @table-annotated → UnclassifiedField",
            """
            type Baz implements Node @table(name: "baz") @node { id: ID! }
            type Plain { name: String }
            type Query { bazById(id: ID @nodeId(typeName: "Plain")): Baz }
            """,
            schema -> {
                var f = (GraphitronField.UnclassifiedField) schema.field("Query", "bazById");
                assertThat(f.reason()).contains("not @table-annotated");
            }),

        SAME_TABLE_WITH_FILTER_SIBLING(
            "composite-PK same-typename `@nodeId` arg + sibling scalar filter arg → QueryTableField "
                + "composes BodyParam.RowIn (PK filter) with BodyParam.Eq (sibling) (R106: filter "
                + "lift puts @nodeId on the same rail as ordinary scalar filter args)",
            """
            type Bar implements Node @table(name: "bar") @node { id: ID! }
            type Query { barsById(ids: [ID!]! @nodeId(typeName: "Bar"), name: String): [Bar!]! }
            """,
            schema -> {
                var f = (no.sikt.graphitron.rewrite.model.QueryField.QueryTableField)
                    schema.field("Query", "barsById");
                var gcf = (no.sikt.graphitron.rewrite.model.GeneratedConditionFilter)
                    f.filters().stream()
                        .filter(no.sikt.graphitron.rewrite.model.GeneratedConditionFilter.class::isInstance)
                        .findFirst().orElseThrow();
                var idIn = (no.sikt.graphitron.rewrite.model.BodyParam.RowIn) gcf.bodyParams().stream()
                    .filter(no.sikt.graphitron.rewrite.model.BodyParam.RowIn.class::isInstance)
                    .findFirst().orElseThrow();
                assertThat(idIn.name()).isEqualTo("ids");
                assertThat(idIn.columns()).hasSize(2);
                assertThat(idIn.extraction()).isInstanceOf(CallSiteExtraction.SkipMismatchedElement.class);
                var nameEq = (no.sikt.graphitron.rewrite.model.BodyParam.Eq) gcf.bodyParams().stream()
                    .filter(no.sikt.graphitron.rewrite.model.BodyParam.Eq.class::isInstance)
                    .filter(bp -> "name".equals(((no.sikt.graphitron.rewrite.model.BodyParam.Eq) bp).name()))
                    .findFirst().orElseThrow();
                assertThat(nameEq.column().sqlName()).isEqualTo("name");
            }),

        SAME_TABLE_WITH_EXPLICIT_LOOKUP_KEY(
            "explicit `@lookupKey` on a same-table `@nodeId` arg re-enables the N×M derived-table "
                + "lookup shape: classifies as QueryLookupTableField with ScalarLookupArg over baz.id "
                + "(R106: same-table @nodeId now defaults to filter; @lookupKey is the deliberate "
                + "opt-in for the lookup shape)",
            """
            type Baz implements Node @table(name: "baz") @node { id: ID! }
            type Query { bazByIds(ids: [ID!]! @nodeId(typeName: "Baz") @lookupKey): [Baz!]! }
            """,
            schema -> {
                var f = (no.sikt.graphitron.rewrite.model.QueryField.QueryLookupTableField)
                    schema.field("Query", "bazByIds");
                var cm = (no.sikt.graphitron.rewrite.model.LookupMapping.ColumnMapping) f.lookupMapping();
                var arg = (no.sikt.graphitron.rewrite.model.LookupMapping.ColumnMapping.LookupArg.ScalarLookupArg)
                    cm.args().get(0);
                assertThat(arg.list()).isTrue();
                assertThat(arg.targetColumn().sqlName()).isEqualTo("id");
                assertThat(arg.extraction()).isInstanceOf(CallSiteExtraction.SkipMismatchedElement.class);
            }),

        FK_TARGET_LOOKUP_KEY_REJECTED(
            "@nodeId @lookupKey on an FK-target arg → UnclassifiedField (FK-target @nodeId is a "
                + "filter, not a lookup, so @lookupKey is meaningless)",
            """
            type Bar implements Node @table(name: "bar") @node { id: ID! }
            type Baz implements Node @table(name: "baz") @node { id: ID! }
            type Query { barsByBaz(bazIds: [ID!]! @nodeId(typeName: "Baz") @lookupKey): [Bar!]! }
            """,
            schema -> {
                var f = (GraphitronField.UnclassifiedField) schema.field("Query", "barsByBaz");
                assertThat(f.reason())
                    .contains("@lookupKey is meaningless on an FK-target @nodeId arg");
            }),

        FIELD_DIRECTIVE_REJECTED(
            "@nodeId @field(name:) on the same arg → UnclassifiedField (the directives target "
                + "different binding axes — key columns come from the resolved NodeType)",
            """
            type Baz implements Node @table(name: "baz") @node { id: ID! }
            type Query { bazById(id: ID @nodeId(typeName: "Baz") @field(name: "id")): Baz }
            """,
            schema -> {
                var f = (GraphitronField.UnclassifiedField) schema.field("Query", "bazById");
                assertThat(f.reason())
                    .contains("@nodeId arg cannot also carry @field");
            });

        final String sdl;
        final Consumer<GraphitronSchema> assertions;
        ArgumentSameTableNodeIdCase(String description, String sdl, Consumer<GraphitronSchema> assertions) {
            this.sdl = sdl;
            this.assertions = assertions;
        }
        @Override public String toString() { return name().toLowerCase().replace('_', ' '); }
    }

    @ParameterizedTest(name = "{0}")
    @EnumSource(ArgumentSameTableNodeIdCase.class)
    void argumentSameTableNodeIdClassification(ArgumentSameTableNodeIdCase tc) {
        tc.assertions.accept(TestSchemaHelper.buildSchema(tc.sdl, FIXTURE_CTX));
    }

    enum ArgumentFkTargetNodeIdCase {
        FK_TARGET_LIST_SINGLE_PK(
            "list `bazIds: [ID!]! @nodeId(typeName: \"Baz\")` on a Bar-returning field where "
                + "bar.id_1 → baz.id is a unique FK → ColumnReferenceArg projects to BodyParam.In "
                + "against bar.id_1 (the FK source column on the field's own table)",
            """
            type Bar implements Node @table(name: "bar") @node { id: ID! }
            type Baz implements Node @table(name: "baz") @node { id: ID! }
            type Query { barsByBaz(bazIds: [ID!]! @nodeId(typeName: "Baz")): [Bar!]! }
            """,
            schema -> {
                var f = (no.sikt.graphitron.rewrite.model.QueryField.QueryTableField)
                    schema.field("Query", "barsByBaz");
                var gcf = (no.sikt.graphitron.rewrite.model.GeneratedConditionFilter)
                    f.filters().stream()
                        .filter(no.sikt.graphitron.rewrite.model.GeneratedConditionFilter.class::isInstance)
                        .findFirst().orElseThrow();
                var bp = (no.sikt.graphitron.rewrite.model.BodyParam.In) gcf.bodyParams().stream()
                    .filter(no.sikt.graphitron.rewrite.model.BodyParam.In.class::isInstance)
                    .findFirst().orElseThrow();
                assertThat(bp.column().sqlName()).isEqualTo("id_1");
                assertThat(bp.extraction()).isInstanceOf(CallSiteExtraction.SkipMismatchedElement.class);
                var skip = (CallSiteExtraction.SkipMismatchedElement) bp.extraction();
                assertThat(skip.decodeMethod().methodName()).isEqualTo("decodeBaz");
            }),

        FK_TARGET_SCALAR_SINGLE_PK(
            "scalar `bazId: ID! @nodeId(typeName: \"Baz\")` → BodyParam.Eq against bar.id_1",
            """
            type Bar implements Node @table(name: "bar") @node { id: ID! }
            type Baz implements Node @table(name: "baz") @node { id: ID! }
            type Query { barByBaz(bazId: ID! @nodeId(typeName: "Baz")): Bar }
            """,
            schema -> {
                var f = (no.sikt.graphitron.rewrite.model.QueryField.QueryTableField)
                    schema.field("Query", "barByBaz");
                var gcf = (no.sikt.graphitron.rewrite.model.GeneratedConditionFilter)
                    f.filters().stream()
                        .filter(no.sikt.graphitron.rewrite.model.GeneratedConditionFilter.class::isInstance)
                        .findFirst().orElseThrow();
                var bp = (no.sikt.graphitron.rewrite.model.BodyParam.Eq) gcf.bodyParams().stream()
                    .filter(no.sikt.graphitron.rewrite.model.BodyParam.Eq.class::isInstance)
                    .findFirst().orElseThrow();
                assertThat(bp.column().sqlName()).isEqualTo("id_1");
            }),

        FK_TARGET_PATHOLOGICAL_KEY_MISMATCH_DEFERRED(
            "@nodeId(typeName: ParentNode) on a child_ref-returning field where the FK targets "
                + "parent_node.alt_key but ParentNode's keyColumn is parent_node.pk_id (FK target ≠ "
                + "NodeType key) → UnclassifiedField with deferred-emission hint, parallel to R24",
            """
            type ParentNode implements Node @table(name: "parent_node") @node { id: ID! }
            type ChildRef @table(name: "child_ref") {
                childId: String! @field(name: "child_id")
            }
            type Query {
                childRefsByParent(parentIds: [ID!]! @nodeId(typeName: "ParentNode")): [ChildRef!]!
            }
            """,
            schema -> {
                var f = (GraphitronField.UnclassifiedField) schema.field("Query", "childRefsByParent");
                assertThat(f.reason())
                    .contains("FK's target columns do not positionally match")
                    .contains("deferred");
            }),

        MULTI_HOP_IDENTITY_CARRYING(
            "R114: 2-hop @reference path from level_c to level_a via level_b. Both adjacent hops "
                + "satisfy the lift predicate, so the carrier ships a CompositeColumnReferenceArg "
                + "whose joinPath has size 2 and whose liftedSourceColumns lives on level_c (the "
                + "parent's own table) and aligns positionally with LevelA's NodeType keys. The "
                + "emitted BodyParam.RowIn binds against level_c.(K1, K2), not joinPath[0].",
            """
            type LevelA implements Node @table(name: "level_a") @node { id: ID! }
            type LevelC @table(name: "level_c") {
                cId: String! @field(name: "c")
            }
            type Query {
                levelCsByLevelA(
                    levelAIds: [ID!]! @nodeId(typeName: "LevelA") @reference(path: [
                        {key: "level_c_level_b_fk"},
                        {key: "level_b_level_a_fk"}
                    ])
                ): [LevelC!]!
            }
            """,
            schema -> {
                var f = (no.sikt.graphitron.rewrite.model.QueryField.QueryTableField)
                    schema.field("Query", "levelCsByLevelA");
                var gcf = (no.sikt.graphitron.rewrite.model.GeneratedConditionFilter)
                    f.filters().stream()
                        .filter(no.sikt.graphitron.rewrite.model.GeneratedConditionFilter.class::isInstance)
                        .findFirst().orElseThrow();
                var bp = (no.sikt.graphitron.rewrite.model.BodyParam.RowIn) gcf.bodyParams().stream()
                    .filter(no.sikt.graphitron.rewrite.model.BodyParam.RowIn.class::isInstance)
                    .findFirst().orElseThrow();
                assertThat(bp.columns())
                    .extracting(c -> c.sqlName())
                    .containsExactly("k1", "k2");
                assertThat(bp.extraction())
                    .isInstanceOf(CallSiteExtraction.SkipMismatchedElement.class);
                var skip = (CallSiteExtraction.SkipMismatchedElement) bp.extraction();
                assertThat(skip.decodeMethod().methodName()).isEqualTo("decodeLevelA");
            });

        final String sdl;
        final Consumer<GraphitronSchema> assertions;
        ArgumentFkTargetNodeIdCase(String description, String sdl, Consumer<GraphitronSchema> assertions) {
            this.sdl = sdl;
            this.assertions = assertions;
        }
        @Override public String toString() { return name().toLowerCase().replace('_', ' '); }
    }

    @ParameterizedTest(name = "{0}")
    @EnumSource(ArgumentFkTargetNodeIdCase.class)
    void argumentFkTargetNodeIdClassification(ArgumentFkTargetNodeIdCase tc) {
        tc.assertions.accept(TestSchemaHelper.buildSchema(tc.sdl, FIXTURE_CTX));
    }

    /**
     * Input-field-side FK-target {@code @nodeId} cases. The positional-correspondence predicate
     * (FK target columns vs NodeType key columns) is lifted into
     * {@link no.sikt.graphitron.rewrite.NodeIdLeafResolver}; the resolver picks
     * {@link no.sikt.graphitron.rewrite.NodeIdLeafResolver.Resolved.FkTarget.DirectFk DirectFk} or
     * {@link no.sikt.graphitron.rewrite.NodeIdLeafResolver.Resolved.FkTarget.TranslatedFk TranslatedFk}
     * once and both call sites consume the variant. Closes the asymmetric-gating gap where
     * {@link FieldBuilder#classifyArgument} ran the predicate but
     * {@link BuildContext#classifyInputField} did not, silently letting the pathological shape
     * through.
     */
    enum InputFieldFkTargetNodeIdCase {
        FK_TARGET_PATHOLOGICAL_KEY_MISMATCH_DEFERRED_INPUT(
            "input-field `[ID!] @nodeId(typeName: ParentNode)` on a child_ref-bound input where the "
                + "FK targets parent_node.alt_key but ParentNode's keyColumn is parent_node.pk_id "
                + "(FK target ≠ NodeType key) → UnclassifiedType for the input (the input field "
                + "surfaces the deferred-emission hint via its Unresolved reason), parallel to the "
                + "arg-side ArgumentFkTargetNodeIdCase.FK_TARGET_PATHOLOGICAL_KEY_MISMATCH_DEFERRED",
            """
            type ParentNode implements Node @table(name: "parent_node") @node { id: ID! }
            input ChildRefFilterInput @table(name: "child_ref") {
                parentIds: [ID!] @nodeId(typeName: "ParentNode")
            }
            type Query { x: String }
            """,
            schema -> {
                // The FK-target with pathological keys lands as Unresolved in classifyInputField,
                // which surfaces as the input type being UnclassifiedType (the same shape
                // SAME_TABLE_TARGET_NOT_NODE asserts on the same-table side).
                var t = schema.type("ChildRefFilterInput");
                assertThat(t).isInstanceOf(GraphitronType.UnclassifiedType.class);
                var u = (GraphitronType.UnclassifiedType) t;
                assertThat(u.reason())
                    .contains("FK's target columns do not positionally match")
                    .contains("deferred");
            }),

        MULTI_HOP_IDENTITY_CARRYING_INPUT(
            "R114: input-field `[ID!] @nodeId(typeName: LevelA) @reference(path: [..., ...])` on a "
                + "level_c-bound input — 2-hop chain that satisfies the lift predicate. The carrier "
                + "is InputField.CompositeColumnReferenceField with joinPath.size() == 2, the column "
                + "tuple = LevelA's NodeType keys (k1, k2), and liftedSourceColumns lives on the "
                + "parent's own table (level_c.(k1, k2)). Mirror of the arg-side multi-hop case.",
            """
            type LevelA implements Node @table(name: "level_a") @node { id: ID! }
            input LevelCFilterInput @table(name: "level_c") {
                levelAIds: [ID!] @nodeId(typeName: "LevelA") @reference(path: [
                    {key: "level_c_level_b_fk"},
                    {key: "level_b_level_a_fk"}
                ])
            }
            type Query { x: String }
            """,
            schema -> {
                var input = (GraphitronType.TableInputType)
                    schema.type("LevelCFilterInput");
                var leaf = input.inputFields().stream()
                    .filter(f -> f.name().equals("levelAIds"))
                    .findFirst().orElseThrow();
                assertThat(leaf).isInstanceOf(no.sikt.graphitron.rewrite.model.InputField.CompositeColumnReferenceField.class);
                var ccrf = (no.sikt.graphitron.rewrite.model.InputField.CompositeColumnReferenceField) leaf;
                assertThat(ccrf.joinPath()).hasSize(2);
                assertThat(ccrf.columns())
                    .extracting(c -> c.sqlName())
                    .containsExactly("k1", "k2");
                // liftedSourceColumns are SQL-name-equal to the NodeType keys (identity-carrying);
                // the table affinity is positional (parent's own table), not encoded on ColumnRef.
                assertThat(ccrf.liftedSourceColumns())
                    .extracting(c -> c.sqlName())
                    .containsExactly("k1", "k2");
            });

        final String sdl;
        final Consumer<GraphitronSchema> assertions;
        InputFieldFkTargetNodeIdCase(String description, String sdl, Consumer<GraphitronSchema> assertions) {
            this.sdl = sdl;
            this.assertions = assertions;
        }
        @Override public String toString() { return name().toLowerCase().replace('_', ' '); }
    }

    @ParameterizedTest(name = "{0}")
    @EnumSource(InputFieldFkTargetNodeIdCase.class)
    void inputFieldFkTargetNodeIdClassification(InputFieldFkTargetNodeIdCase tc) {
        tc.assertions.accept(TestSchemaHelper.buildSchema(tc.sdl, FIXTURE_CTX));
    }

    // ===== Classifier: @asConnection + same-table @nodeId leaf advisory =====
    //
    // Required same-table @nodeId leaves classify normally; the classifier emits a LOG.warn
    // (covered in AsConnectionSameTableWarnFormatTest). Optional leaves are silent. The walk
    // is order-independent: ∃-required folds the carrier to Required regardless of SDL
    // position, but the runtime shape ships either way. FK-target leaves are unaffected.

    private static final String CONNECTION_DECLS = """
        type BazConnection { edges: [BazEdge!]! pageInfo: PageInfo! }
        type BazEdge { node: Baz! cursor: String! }
        type PageInfo { hasNextPage: Boolean! hasPreviousPage: Boolean! startCursor: String endCursor: String }
        """;

    private static void assertConnectionShapeWithPkInFilter(GraphitronSchema schema, String fieldName) {
        var f = (no.sikt.graphitron.rewrite.model.QueryField.QueryTableField)
            schema.field("Query", fieldName);
        assertThat(f.returnType().wrapper())
            .isInstanceOf(no.sikt.graphitron.rewrite.model.FieldWrapper.Connection.class);
        var gcf = (no.sikt.graphitron.rewrite.model.GeneratedConditionFilter)
            f.filters().stream()
                .filter(no.sikt.graphitron.rewrite.model.GeneratedConditionFilter.class::isInstance)
                .findFirst().orElseThrow();
        var inFilters = gcf.bodyParams().stream()
            .filter(no.sikt.graphitron.rewrite.model.BodyParam.In.class::isInstance)
            .map(no.sikt.graphitron.rewrite.model.BodyParam.In.class::cast)
            .toList();
        assertThat(inFilters).hasSize(1);
        var bp = inFilters.get(0);
        assertThat(bp.column().sqlName()).isEqualTo("id");
        assertThat(bp.extraction()).isInstanceOf(CallSiteExtraction.SkipMismatchedElement.class);
        assertThat(f.orderBy()).isNotNull();
        assertThat(f.pagination()).isNotNull();
    }

    enum NodeIdConnectionAdvisoryCase {
        ASCONNECTION_PLUS_REQUIRED_ARGUMENT_SAME_TABLE_NODEID_ALLOWED(
            "@asConnection field with a required (NonNull outer) top-level same-table @nodeId arg "
                + "→ classifies normally with WHERE pk IN (...) + pagination; the production-shape "
                + "case (mirrors opptak-subgraph's Query.kompetanseregelverkGittIdV2). Warn fires "
                + "at LOG.warn — the surface is covered in AsConnectionSameTableWarnFormatTest.",
            """
            type Baz implements Node @table(name: "baz") @node { id: ID! }
            """ + CONNECTION_DECLS + """
            type Query {
                bazByIds(ids: [ID!]! @nodeId(typeName: "Baz")): BazConnection @asConnection
            }
            """,
            schema -> assertConnectionShapeWithPkInFilter(schema, "bazByIds")),

        ASCONNECTION_PLUS_OPTIONAL_ARGUMENT_SAME_TABLE_NODEID_ALLOWED(
            "@asConnection field with an optional (nullable outer) top-level same-table @nodeId arg "
                + "→ classifies normally; warn does NOT fire (∃-required predicate is False here)",
            """
            type Baz implements Node @table(name: "baz") @node { id: ID! }
            """ + CONNECTION_DECLS + """
            type Query {
                bazes(ids: [ID!] @nodeId(typeName: "Baz")): BazConnection @asConnection
            }
            """,
            schema -> assertConnectionShapeWithPkInFilter(schema, "bazes")),

        ASCONNECTION_PLUS_REQUIRED_INPUT_FIELD_SAME_TABLE_NODEID_ALLOWED(
            "@asConnection field whose required input arg carries a required same-table @nodeId "
                + "leaf (every wrapper non-null) → classifies normally; warn fires",
            """
            type Baz implements Node @table(name: "baz") @node { id: ID! }
            """ + CONNECTION_DECLS + """
            input BazFilter @table(name: "baz") {
                ids: [ID!]! @nodeId(typeName: "Baz")
            }
            type Query {
                bazes(filter: BazFilter!): BazConnection @asConnection
            }
            """,
            schema -> {
                var f = (no.sikt.graphitron.rewrite.model.QueryField.QueryTableField)
                    schema.field("Query", "bazes");
                assertThat(f.returnType().wrapper())
                    .isInstanceOf(no.sikt.graphitron.rewrite.model.FieldWrapper.Connection.class);
            }),

        ASCONNECTION_PLUS_OPTIONAL_INPUT_FIELD_SAME_TABLE_NODEID_ALLOWED(
            "@asConnection field whose nullable input arg carries a nullable same-table @nodeId "
                + "leaf (legacy R50 input-field shape) → classifies normally; warn does NOT fire",
            """
            type Baz implements Node @table(name: "baz") @node { id: ID! }
            """ + CONNECTION_DECLS + """
            input BazFilter @table(name: "baz") {
                ids: [ID!] @nodeId(typeName: "Baz")
            }
            type Query {
                bazes(filter: BazFilter): BazConnection @asConnection
            }
            """,
            schema -> {
                var f = (no.sikt.graphitron.rewrite.model.QueryField.QueryTableField)
                    schema.field("Query", "bazes");
                assertThat(f.returnType().wrapper())
                    .isInstanceOf(no.sikt.graphitron.rewrite.model.FieldWrapper.Connection.class);
            }),

        ASCONNECTION_PLUS_NESTED_INPUT_REQUIRED_NULLABLE_OUTER_ALLOWED(
            "@asConnection field whose nullable input arg carries a required same-table @nodeId "
                + "leaf → conjunctive rule: outer nullable ⇒ path nullable ⇒ classifies normally; "
                + "warn does NOT fire (pins the conjunctive rule, not per-step)",
            """
            type Baz implements Node @table(name: "baz") @node { id: ID! }
            """ + CONNECTION_DECLS + """
            input BazFilter @table(name: "baz") {
                ids: [ID!]! @nodeId(typeName: "Baz")
            }
            type Query {
                bazes(filter: BazFilter): BazConnection @asConnection
            }
            """,
            schema -> {
                var f = (no.sikt.graphitron.rewrite.model.QueryField.QueryTableField)
                    schema.field("Query", "bazes");
                assertThat(f.returnType().wrapper())
                    .isInstanceOf(no.sikt.graphitron.rewrite.model.FieldWrapper.Connection.class);
            }),

        ASCONNECTION_PLUS_MIXED_NULLABILITY_REQUIRED_FIRST_ALLOWED(
            "two same-table @nodeId args, required declared first then optional → classifies "
                + "normally (∃-required predicate is True; warn fires regardless of SDL position)",
            """
            type Baz implements Node @table(name: "baz") @node { id: ID! }
            """ + CONNECTION_DECLS + """
            type Query {
                bazes(
                    requiredIds: [ID!]! @nodeId(typeName: "Baz"),
                    optionalIds: [ID!] @nodeId(typeName: "Baz")
                ): BazConnection @asConnection
            }
            """,
            schema -> {
                var f = (no.sikt.graphitron.rewrite.model.QueryField.QueryTableField)
                    schema.field("Query", "bazes");
                assertThat(f.returnType().wrapper())
                    .isInstanceOf(no.sikt.graphitron.rewrite.model.FieldWrapper.Connection.class);
            }),

        ASCONNECTION_PLUS_MIXED_NULLABILITY_OPTIONAL_FIRST_ALLOWED(
            "two same-table @nodeId args, optional declared first then required → classifies "
                + "normally (∃-required is order-independent; warn fires either way)",
            """
            type Baz implements Node @table(name: "baz") @node { id: ID! }
            """ + CONNECTION_DECLS + """
            type Query {
                bazes(
                    optionalIds: [ID!] @nodeId(typeName: "Baz"),
                    requiredIds: [ID!]! @nodeId(typeName: "Baz")
                ): BazConnection @asConnection
            }
            """,
            schema -> {
                var f = (no.sikt.graphitron.rewrite.model.QueryField.QueryTableField)
                    schema.field("Query", "bazes");
                assertThat(f.returnType().wrapper())
                    .isInstanceOf(no.sikt.graphitron.rewrite.model.FieldWrapper.Connection.class);
            }),

        ASCONNECTION_PLUS_FK_TARGET_ARG_NODEID_ALLOWED(
            "@asConnection field with a top-level FK-target @nodeId arg → classifies normally "
                + "(filter narrows the result; seek paginates within the filtered set; warn never fires)",
            """
            type Bar implements Node @table(name: "bar") @node { id: ID! }
            type Baz implements Node @table(name: "baz") @node { id: ID! }
            type BarConnection { edges: [BarEdge!]! pageInfo: PageInfo! }
            type BarEdge { node: Bar! cursor: String! }
            type PageInfo { hasNextPage: Boolean! hasPreviousPage: Boolean! startCursor: String endCursor: String }
            type Query {
                barsByBaz(bazIds: [ID!]! @nodeId(typeName: "Baz")): BarConnection @asConnection
            }
            """,
            schema -> {
                var f = schema.field("Query", "barsByBaz");
                assertThat(f).isNotInstanceOf(GraphitronField.UnclassifiedField.class);
            });

        final String sdl;
        final Consumer<GraphitronSchema> assertions;
        NodeIdConnectionAdvisoryCase(String description, String sdl, Consumer<GraphitronSchema> assertions) {
            this.sdl = sdl;
            this.assertions = assertions;
        }
        @Override public String toString() { return name().toLowerCase().replace('_', ' '); }
    }

    @ParameterizedTest(name = "{0}")
    @EnumSource(NodeIdConnectionAdvisoryCase.class)
    void asConnectionPlusSameTableNodeIdAdvisory(NodeIdConnectionAdvisoryCase tc) {
        tc.assertions.accept(TestSchemaHelper.buildSchema(tc.sdl, FIXTURE_CTX));
    }
}
