package no.sikt.graphitron.rewrite;

import no.sikt.graphitron.rewrite.model.CallSiteCompaction;
import no.sikt.graphitron.rewrite.model.CallSiteExtraction;
import no.sikt.graphitron.rewrite.model.ChildField;
import no.sikt.graphitron.rewrite.model.ColumnRef;
import no.sikt.graphitron.rewrite.model.GraphitronField;
import no.sikt.graphitron.rewrite.model.GraphitronType;
import no.sikt.graphitron.rewrite.model.InputField;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.EnumSource;

import java.nio.file.Path;
import java.util.List;
import java.util.Map;
import java.util.function.Consumer;

import static no.sikt.graphitron.common.configuration.TestConfiguration.DEFAULT_OUTPUT_PACKAGE;
import static org.assertj.core.api.Assertions.assertThat;
import no.sikt.graphitron.rewrite.test.tier.PipelineTier;

/**
 * SDL → classified-variant pipeline tests for the node-id path. Exercises the input-side
 * (single-column carriers with {@link no.sikt.graphitron.rewrite.model.CallSiteExtraction.NodeIdDecodeKeys}
 * and the {@code Composite*} variants), output-side ({@link ChildField.ColumnField} /
 * {@link ChildField.CompositeColumnField} with {@link no.sikt.graphitron.rewrite.model.CallSiteCompaction.NodeIdEncodeKeys}),
 * and type-level {@link GraphitronType.NodeType} synthesis for
 * tables whose jOOQ class exposes {@code __NODE_TYPE_ID} + {@code __NODE_KEY_COLUMNS} constants
 * (synthesized route) as well as the SDL-declared {@code @node} / {@code @nodeId} directive paths.
 *
 * <p>Uses the {@code no.sikt.graphitron.rewrite.nodeidfixture} catalog — generated by
 * {@code NodeIdFixtureGenerator} in {@code graphitron-fixtures-codegen}, which extends
 * the upstream jOOQ {@code JavaGenerator} and hard-codes {@code __NODE_TYPE_ID} /
 * {@code __NODE_KEY_COLUMNS} on {@code bar} (composite key) and {@code baz} (single key). The
 * generator is a faithful model of Sikt's production {@code KjerneJooqGenerator}, so the
 * classifier is tested against real generator output rather than a hand-edited approximation.
 * <ul>
 *   <li>{@code bar} — composite-key NodeType; {@code __NODE_TYPE_ID = "Bar"},
 *       {@code __NODE_KEY_COLUMNS = { BAR.ID_1, BAR.ID_2 }}. FK {@code bar.id_1 -> baz.id}
 *       supports NodeIdReferenceField tests.</li>
 *   <li>{@code baz} — single-key NodeType; reference target for {@code bar}.</li>
 *   <li>{@code qux} — plain table; no metadata. Negative-case fixture.</li>
 *   <li>{@code parent_node} — single-key NodeType keyed on {@code PK_ID}, with a separate
 *       {@code ALT_KEY} unique column targeted by {@code child_ref.parent_alt_key}'s FK.
 *       The FK target ({@code alt_key}) does not positionally match the NodeType's keyColumn
 *       ({@code pk_id}), forcing the rooted-at-parent JOIN-with-projection path.</li>
 *   <li>{@code child_ref} — plain table; FK {@code parent_alt_key -> parent_node.alt_key} is
 *       the rooted-at-parent fixture's drive surface.</li>
 * </ul>
 */
@PipelineTier
class NodeIdPipelineTest {

    private static final String FIXTURE_JOOQ_PACKAGE = "no.sikt.graphitron.rewrite.nodeidfixture";
    private static final RewriteContext FIXTURE_CTX = new RewriteContext(
        List.of(), Path.of(""), Path.of(""),
        DEFAULT_OUTPUT_PACKAGE, FIXTURE_JOOQ_PACKAGE,
        Map.of()
    );

    // ===== Type-level NodeType synthesis =====

    enum TypeCase {
        METADATA_ONLY_NO_PROMOTION(
            "`@table` on a metadata-carrying table without `implements Node @node` stays a TableType "
                + "(NodeType promotion is opt-in; auto-promotion previously collided typeIds across "
                + "tables that shared `__NODE_TYPE_ID`)",
            """
            type Foo @table(name: "bar") { name: String }
            type Query { foo: Foo }
            """,
            schema -> assertThat(schema.type("Foo")).isInstanceOf(GraphitronType.TableType.class)),

        NODE_AND_METADATA_AGREE(
            "`@node(typeId:, keyColumns:)` matching metadata exactly → NodeType (accepted)",
            """
            type Foo implements Node @table(name: "bar") @node(typeId: "Bar", keyColumns: ["id_1", "id_2"]) { id: ID! name: String }
            type Query { foo: Foo }
            """,
            schema -> {
                var t = (GraphitronType.NodeType) schema.type("Foo");
                assertThat(t.typeId()).isEqualTo("Bar");
                assertThat(t.nodeKeyColumns()).extracting(ColumnRef::sqlName)
                    .containsExactly("id_1", "id_2");
            }),

        NODE_WITHOUT_ARGS_DELEGATES_TO_METADATA(
            "`@node` with neither `typeId` nor `keyColumns` delegates to metadata on both axes",
            """
            type Foo implements Node @table(name: "bar") @node { id: ID! name: String }
            type Query { foo: Foo }
            """,
            schema -> {
                var t = (GraphitronType.NodeType) schema.type("Foo");
                assertThat(t.typeId()).isEqualTo("Bar");
                assertThat(t.nodeKeyColumns()).extracting(ColumnRef::sqlName)
                    .containsExactly("id_1", "id_2");
            }),

        TYPE_ID_DISAGREES_SDL_WINS(
            "`@node(typeId: \"Foo\")` on a metadata-carrying table → NodeType with SDL typeId (durability: SDL author pins wire format)",
            """
            type Foo implements Node @table(name: "bar") @node(typeId: "Foo", keyColumns: ["id_1", "id_2"]) { id: ID! name: String }
            type Query { foo: Foo }
            """,
            schema -> {
                var t = (GraphitronType.NodeType) schema.type("Foo");
                assertThat(t.typeId()).isEqualTo("Foo");
                assertThat(t.nodeKeyColumns()).extracting(ColumnRef::sqlName)
                    .containsExactly("id_1", "id_2");
            }),

        KEY_COLUMNS_ORDER_ONLY_DIFFERS_SDL_WINS(
            "`@node(keyColumns: [...])` with same set but different order from metadata → NodeType with SDL order (WARN logged but not blocking)",
            """
            type Foo implements Node @table(name: "bar") @node(typeId: "Bar", keyColumns: ["id_2", "id_1"]) { id: ID! name: String }
            type Query { foo: Foo }
            """,
            schema -> {
                var t = (GraphitronType.NodeType) schema.type("Foo");
                assertThat(t.typeId()).isEqualTo("Bar");
                assertThat(t.nodeKeyColumns()).extracting(ColumnRef::sqlName)
                    .containsExactly("id_2", "id_1");
            }),

        KEY_COLUMNS_SET_DIFFERS_HARD_ERROR(
            "`@node(keyColumns: [...])` with different *set* from metadata → UnclassifiedType (one side wrong about the schema)",
            """
            type Foo implements Node @table(name: "bar") @node(keyColumns: ["id_1"]) { id: ID! name: String }
            type Query { foo: Foo }
            """,
            schema -> {
                var t = (GraphitronType.UnclassifiedType) schema.type("Foo");
                assertThat(t.reason())
                    .contains("column sets are different")
                    .contains("[\"id_1\"]")
                    .contains("[\"id_1\", \"id_2\"]");
            }),

        TYPE_ID_ONLY_DISAGREES_KEY_COLUMNS_OMITTED(
            "`@node(typeId: \"Foo\")` without keyColumns → NodeType (SDL typeId wins silently; keyColumns fall through to metadata)",
            """
            type Foo implements Node @table(name: "bar") @node(typeId: "Foo") { id: ID! name: String }
            type Query { foo: Foo }
            """,
            schema -> {
                var t = (GraphitronType.NodeType) schema.type("Foo");
                assertThat(t.typeId()).isEqualTo("Foo");
                assertThat(t.nodeKeyColumns()).extracting(ColumnRef::sqlName)
                    .containsExactly("id_1", "id_2");
            }),

        NODE_WITHOUT_IMPLEMENTS_NODE(
            "`@node` on a type that does not `implements Node` → UnclassifiedType (schema contract violation)",
            """
            type Foo @table(name: "bar") @node { name: String }
            type Query { foo: Foo }
            """,
            schema -> {
                var t = (GraphitronType.UnclassifiedType) schema.type("Foo");
                assertThat(t.reason()).contains("implements Node");
            }),

        NO_METADATA_NO_NODE(
            "`@table` on a table without metadata → TableType (no synthesis)",
            """
            type Foo @table(name: "qux") { name: String }
            type Query { foo: Foo }
            """,
            schema -> assertThat(schema.type("Foo")).isInstanceOf(GraphitronType.TableType.class)),

        NODE_ONLY_NO_METADATA_TYPEID_DECLARED(
            "`@node(typeId:)` without keyColumns and no metadata → NodeType with SDL typeId and PK fallback (R3)",
            """
            type Foo implements Node @table(name: "qux") @node(typeId: "Foo") { id: ID! name: String }
            type Query { foo: Foo }
            """,
            schema -> {
                var t = (GraphitronType.NodeType) schema.type("Foo");
                assertThat(t.typeId()).isEqualTo("Foo");
                assertThat(t.nodeKeyColumns()).extracting(ColumnRef::sqlName)
                    .containsExactly("name");
            }),

        NODE_ONLY_NO_METADATA_DEFAULTS_FROM_SDL(
            "`@node` with no args and no metadata → NodeType with typeId = SDL type name and PK fallback (R3)",
            """
            type Foo implements Node @table(name: "qux") @node { id: ID! name: String }
            type Query { foo: Foo }
            """,
            schema -> {
                var t = (GraphitronType.NodeType) schema.type("Foo");
                assertThat(t.typeId()).isEqualTo("Foo");
                assertThat(t.nodeKeyColumns()).extracting(ColumnRef::sqlName)
                    .containsExactly("name");
            }),

        TYPE_ID_COLLISION_DEMOTES_BOTH(
            "two NodeTypes with the same typeId → both demoted to UnclassifiedType (R4a registry uniqueness)",
            """
            type Foo implements Node @table(name: "bar") @node(typeId: "Shared") { id: ID! name: String }
            type Zed implements Node @table(name: "qux") @node(typeId: "Shared") { id: ID! name: String }
            type Query { foo: Foo zed: Zed }
            """,
            schema -> {
                assertThat(schema.type("Foo")).isInstanceOf(GraphitronType.UnclassifiedType.class);
                assertThat(schema.type("Zed")).isInstanceOf(GraphitronType.UnclassifiedType.class);
                var fooReason = ((GraphitronType.UnclassifiedType) schema.type("Foo")).reason();
                assertThat(fooReason)
                    .contains("typeId 'Shared'")
                    .contains("Foo, Zed")
                    .contains("nondeterministic");
            }),

        METADATA_ONLY_TYPES_DO_NOT_COLLIDE(
            "two `@table`-only types backed by metadata-carrying tables stay TableType — no NodeType "
                + "promotion, so no typeId collision even when the tables share `__NODE_TYPE_ID`-style "
                + "metadata. Regression for the sis bug where ~200 `@table` event types were silently "
                + "promoted and then mass-demoted via the registry-uniqueness check.",
            """
            type Foo @table(name: "bar") { name: String }
            type Zed @table(name: "baz") { name: String }
            type Query { foo: Foo zed: Zed }
            """,
            schema -> {
                assertThat(schema.type("Foo")).isInstanceOf(GraphitronType.TableType.class);
                assertThat(schema.type("Zed")).isInstanceOf(GraphitronType.TableType.class);
            });

        final String sdl;
        final Consumer<GraphitronSchema> assertions;
        TypeCase(String description, String sdl, Consumer<GraphitronSchema> assertions) {
            this.sdl = sdl;
            this.assertions = assertions;
        }
        @Override public String toString() { return name().toLowerCase().replace('_', ' '); }
    }

    @ParameterizedTest(name = "{0}")
    @EnumSource(TypeCase.class)
    void typeLevelNodeSynthesis(TypeCase tc) {
        tc.assertions.accept(TestSchemaHelper.buildSchema(tc.sdl, FIXTURE_CTX));
    }

    @org.junit.jupiter.api.Test
    void nodeTypeWireFormat_independentOfSdlTypeName() {
        // Opacity invariant: an opaque ID encodes against (typeId, keyColumns), neither of
        // which is the SDL type name. Renaming the SDL type while pinning @node(typeId:) and
        // pointing at the same table must produce a structurally identical NodeType — the
        // wire-format carrier the encoder and dispatcher consult. If a refactor ever leaked
        // the SDL type name into typeId or keyColumns, every ID issued before the rename
        // would silently stop resolving.
        String sdlOriginal = """
            type Foo implements Node @table(name: "bar") @node(typeId: "FrozenWire") { id: ID! name: String }
            type Query { foo: Foo }
            """;
        String sdlRenamed = """
            type RenamedFoo implements Node @table(name: "bar") @node(typeId: "FrozenWire") { id: ID! name: String }
            type Query { foo: RenamedFoo }
            """;
        var schemaA = TestSchemaHelper.buildSchema(sdlOriginal, FIXTURE_CTX);
        var schemaB = TestSchemaHelper.buildSchema(sdlRenamed, FIXTURE_CTX);

        var ntA = (GraphitronType.NodeType) schemaA.type("Foo");
        var ntB = (GraphitronType.NodeType) schemaB.type("RenamedFoo");

        assertThat(ntA.typeId()).isEqualTo("FrozenWire");
        assertThat(ntB.typeId()).isEqualTo(ntA.typeId());
        assertThat(ntB.nodeKeyColumns()).extracting(ColumnRef::sqlName)
            .isEqualTo(ntA.nodeKeyColumns().stream().map(ColumnRef::sqlName).toList());
    }

    // ===== Input side =====

    enum InputCase {
        IMPLICIT_ID(
            "input `id: ID!` on a composite-PK node-type table → CompositeColumnField with NodeIdDecodeKeys.SkipMismatchedElement (post-R50; synthesized route)",
            """
            input Foo @table(name: "bar") { id: ID! }
            type Query { x: String }
            """,
            schema -> {
                var t = (GraphitronType.TableInputType) schema.type("Foo");
                var f = (InputField.CompositeColumnField) t.inputFields().get(0);
                assertThat(f.columns()).extracting(ColumnRef::sqlName)
                    .containsExactly("id_1", "id_2");
                assertThat(f.extraction())
                    .isInstanceOf(no.sikt.graphitron.rewrite.model.CallSiteExtraction.SkipMismatchedElement.class);
                assertThat(f.extraction().decodeMethod().methodName()).isEqualTo("decodeBar");
            }),

        EXPLICIT_PERSON_ID(
            "input `personId: ID! @field(name: \"PERSON_ID\")` on a composite-PK node-type table → CompositeColumnField with NodeIdDecodeKeys (PERSON_ID has no column, nodeId metadata wins)",
            """
            input Foo @table(name: "bar") { personId: ID! @field(name: "PERSON_ID") }
            type Query { x: String }
            """,
            schema -> {
                var t = (GraphitronType.TableInputType) schema.type("Foo");
                var f = (InputField.CompositeColumnField) t.inputFields().get(0);
                assertThat(f.columns()).extracting(ColumnRef::sqlName)
                    .containsExactly("id_1", "id_2");
                assertThat(f.extraction())
                    .isInstanceOf(no.sikt.graphitron.rewrite.model.CallSiteExtraction.SkipMismatchedElement.class);
            }),

        EXPLICIT_NODE_ID_DIRECTIVE(
            "input `id: ID! @nodeId` on a @table input whose table is also backed by a composite-PK NodeType → CompositeColumnReferenceField with NodeIdDecodeKeys.SkipMismatchedElement (post-R50; arity > 1)",
            """
            type Bar @table(name: "bar") @node { id: ID! @nodeId }
            input Foo @table(name: "bar") { id: ID! @nodeId }
            type Query { x: String }
            """,
            schema -> {
                var t = (GraphitronType.TableInputType) schema.type("Foo");
                var f = (InputField.CompositeColumnReferenceField) t.inputFields().get(0);
                assertThat(f.columns()).extracting(ColumnRef::sqlName)
                    .containsExactly("id_1", "id_2");
                assertThat(f.joinPath()).isEmpty();
                assertThat(f.extraction())
                    .isInstanceOf(no.sikt.graphitron.rewrite.model.CallSiteExtraction.SkipMismatchedElement.class);
                assertThat(f.extraction().decodeMethod().methodName()).isEqualTo("decodeBar");
            }),

        BARE_NODE_ID_NO_OBJECT_TYPE(
            "input `id: ID! @nodeId` on a @table whose table has no matching object type → friendly error",
            """
            input Foo @table(name: "bar") { id: ID! @nodeId }
            type Query { x: String }
            """,
            schema -> {
                var t = (GraphitronType.UnclassifiedType) schema.type("Foo");
                assertThat(t.reason())
                    .contains("@nodeId without typeName: cannot infer node type")
                    .contains("no @table-annotated object type maps to table 'bar'")
                    .contains("Add typeName: explicitly");
            }),

        BARE_NODE_ID_AMBIGUOUS_OBJECT_TYPES(
            "input `id: ID! @nodeId` on a @table shared by two object types → friendly ambiguity error",
            """
            type BarA @table(name: "bar") @node { id: ID! @nodeId }
            type BarB @table(name: "bar") @node { id: ID! @nodeId }
            input Foo @table(name: "bar") { id: ID! @nodeId }
            type Query { a: BarA b: BarB }
            """,
            schema -> {
                var t = (GraphitronType.UnclassifiedType) schema.type("Foo");
                assertThat(t.reason())
                    .contains("@nodeId without typeName: is ambiguous")
                    .contains("multiple object types map to table 'bar'")
                    .contains("BarA")
                    .contains("BarB")
                    .contains("Specify typeName: explicitly");
            }),

        ACCESSOR_MISSING(
            "plain ID field on a table without node-id metadata → TableInputType fails, type becomes UnclassifiedType",
            """
            input Foo @table(name: "qux") { id: ID! }
            type Query { x: String }
            """,
            schema -> assertThat(schema.type("Foo")).isInstanceOf(GraphitronType.UnclassifiedType.class)),

        LIST_VARIANT(
            "list ID input skips the node-id check (list gate) → UnclassifiedType",
            """
            input Foo @table(name: "bar") { id: [ID!]! }
            type Query { x: String }
            """,
            schema -> assertThat(schema.type("Foo")).isInstanceOf(GraphitronType.UnclassifiedType.class));

        final String sdl;
        final Consumer<GraphitronSchema> assertions;
        InputCase(String description, String sdl, Consumer<GraphitronSchema> assertions) {
            this.sdl = sdl;
            this.assertions = assertions;
        }
        @Override public String toString() { return name().toLowerCase().replace('_', ' '); }
    }

    @ParameterizedTest(name = "{0}")
    @EnumSource(InputCase.class)
    void inputNodeIdClassification(InputCase tc) {
        tc.assertions.accept(TestSchemaHelper.buildSchema(tc.sdl, FIXTURE_CTX));
    }

    // ===== Input reference side =====

    enum InputReferenceCase {
        REFERENCE_TO_NODE_TYPE(
            "input `relatedId: ID! @nodeId(typeName: 'Baz')` on bar table → ColumnReferenceField with NodeIdDecodeKeys.SkipMismatchedElement (post-R50; arity-1 single-PK target)",
            """
            type Baz @table(name: "baz") { id: ID! }
            input Foo @table(name: "bar") { relatedId: ID! @nodeId(typeName: "Baz") }
            type Query { x: String }
            """,
            schema -> {
                var t = (GraphitronType.TableInputType) schema.type("Foo");
                var f = (InputField.ColumnReferenceField) t.inputFields().get(0);
                assertThat(f.typeName()).isEqualTo("ID");
                assertThat(f.column().sqlName()).isEqualTo("id");
                assertThat(f.joinPath()).hasSize(1);
                assertThat(f.extraction())
                    .isInstanceOf(no.sikt.graphitron.rewrite.model.CallSiteExtraction.SkipMismatchedElement.class);
                assertThat(((no.sikt.graphitron.rewrite.model.CallSiteExtraction.NodeIdDecodeKeys) f.extraction())
                    .decodeMethod().methodName()).isEqualTo("decodeBaz");
            }),

        TARGET_NOT_A_NODE_TYPE(
            "input `relatedId: ID! @nodeId(typeName: 'Qux')` where Qux is not a NodeType → UnclassifiedType",
            """
            type Qux @table(name: "qux") { name: String }
            input Foo @table(name: "bar") { relatedId: ID! @nodeId(typeName: "Qux") }
            type Query { x: String }
            """,
            schema -> assertThat(schema.type("Foo")).isInstanceOf(GraphitronType.UnclassifiedType.class)),

        LIST_VARIANT(
            "list `[ID!]!` with @nodeId(typeName:) and no FK from source to target → UnclassifiedType (no FK from 'qux' to 'baz')",
            """
            type Baz @table(name: "baz") { id: ID! }
            input Foo @table(name: "qux") { relatedId: [ID!]! @nodeId(typeName: "Baz") }
            type Query { x: String }
            """,
            schema -> assertThat(schema.type("Foo")).isInstanceOf(GraphitronType.UnclassifiedType.class)),

        NO_FK_PATH(
            "input `relatedId: ID! @nodeId(typeName: 'Baz')` where no FK from qux to baz → UnclassifiedType (path resolver rejects)",
            """
            type Baz @table(name: "baz") { id: ID! }
            input Foo @table(name: "qux") { relatedId: ID! @nodeId(typeName: "Baz") }
            type Query { x: String }
            """,
            schema -> assertThat(schema.type("Foo")).isInstanceOf(GraphitronType.UnclassifiedType.class)),

        NODE_TARGET_NO_METADATA_PK_FALLBACK(
            "input `id: ID! @nodeId(typeName: 'Qux')` where Qux has @node but its table has no NodeId metadata → ColumnReferenceField via catalog PK fallback (regression: pre-fix, the empty keyColumns list propagated into CompositeColumnReferenceField and tripped the arity invariant)",
            """
            type Qux implements Node @table(name: "qux") @node { id: ID! name: String }
            input Foo @table(name: "qux") { id: ID! @nodeId(typeName: "Qux") }
            type Query { x: String }
            """,
            schema -> {
                var t = (GraphitronType.TableInputType) schema.type("Foo");
                var f = (InputField.ColumnReferenceField) t.inputFields().get(0);
                assertThat(f.column().sqlName()).isEqualTo("name");
                assertThat(f.joinPath()).isEmpty();
            });

        final String sdl;
        final Consumer<GraphitronSchema> assertions;
        InputReferenceCase(String description, String sdl, Consumer<GraphitronSchema> assertions) {
            this.sdl = sdl;
            this.assertions = assertions;
        }
        @Override public String toString() { return name().toLowerCase().replace('_', ' '); }
    }

    @ParameterizedTest(name = "{0}")
    @EnumSource(InputReferenceCase.class)
    void inputNodeIdReferenceClassification(InputReferenceCase tc) {
        tc.assertions.accept(TestSchemaHelper.buildSchema(tc.sdl, FIXTURE_CTX));
    }

    // ===== FK-qualifier synthesis shim (post-R50 successor of IdReferenceField) =====

    /**
     * Synthesis-shim cases that, post-R50, route the FK-qualifier hit onto
     * {@link InputField.ColumnReferenceField} (or
     * {@link InputField.CompositeColumnReferenceField} for composite-PK FK targets) carrying
     * {@link CallSiteExtraction.NodeIdDecodeKeys.SkipMismatchedElement} plus the resolved FK
     * joinPath. All use the nodeidfixture catalog so that
     * {@code catalog.nodeIdMetadata("baz")} returns present (the shim's gate condition).
     * {@code bar} carries FK {@code bar_id_1_fkey} to {@code baz}; the qualifier map keys for
     * that FK are {@code "1_baz_id"} (raw), {@code "1bazid"} (camelCase), and
     * {@code "1bazids"} (plural camelCase), all used via explicit {@code @field(name:)} since
     * the qualifier starts with a digit and therefore cannot appear as a bare GraphQL field
     * name.
     */
    enum InputIdReferenceCase {
        SHIM_RAW_QUALIFIER_KEY(
            "@field(name: \"1_baz_id\") hits raw-qualifier map key → ColumnReferenceField with NodeIdDecodeKeys",
            """
            type Baz @table(name: "baz") { id: ID! }
            input Foo @table(name: "bar") {
              barRef: [ID!] @field(name: "1_baz_id")
            }
            type Query { x: String }
            """,
            schema -> {
                var tit = (GraphitronType.TableInputType) schema.type("Foo");
                var f = (InputField.ColumnReferenceField) tit.inputFields().get(0);
                assertThat(f.list()).isTrue();
                assertThat(f.column().sqlName()).isEqualTo("id");
                assertThat(f.extraction()).isInstanceOf(CallSiteExtraction.SkipMismatchedElement.class);
                assertThat(f.joinPath()).hasSize(1);
            }),

        SHIM_PLURAL_CAMEL_KEY(
            "@field(name: \"1bazids\") hits plural camelCase map key → ColumnReferenceField with NodeIdDecodeKeys",
            """
            type Baz @table(name: "baz") { id: ID! }
            input Foo @table(name: "bar") {
              barRef: [ID!] @field(name: "1bazids")
            }
            type Query { x: String }
            """,
            schema -> {
                var tit = (GraphitronType.TableInputType) schema.type("Foo");
                var f = (InputField.ColumnReferenceField) tit.inputFields().get(0);
                assertThat(f.list()).isTrue();
                assertThat(f.extraction()).isInstanceOf(CallSiteExtraction.SkipMismatchedElement.class);
            }),

        SHIM_SINGULAR_CAMEL_KEY(
            "scalar ID @field(name: \"1bazid\") hits singular camelCase map key → ColumnReferenceField with NodeIdDecodeKeys (list=false)",
            """
            type Baz @table(name: "baz") { id: ID! }
            input Foo @table(name: "bar") {
              barRef: ID @field(name: "1bazid")
            }
            type Query { x: String }
            """,
            schema -> {
                var tit = (GraphitronType.TableInputType) schema.type("Foo");
                var f = (InputField.ColumnReferenceField) tit.inputFields().get(0);
                assertThat(f.list()).isFalse();
                assertThat(f.extraction()).isInstanceOf(CallSiteExtraction.SkipMismatchedElement.class);
            }),

        SHIM_BARE_ID_FALLS_THROUGH(
            "bare id: ID on a KjerneJooqGenerator composite-PK table — qualifier map miss → falls through to CompositeColumnField with NodeIdDecodeKeys (post-R50)",
            """
            input Foo @table(name: "bar") {
              id: ID
            }
            type Query { x: String }
            """,
            schema -> {
                var tit = (GraphitronType.TableInputType) schema.type("Foo");
                assertThat(tit.inputFields().get(0)).isInstanceOf(InputField.CompositeColumnField.class);
            });

        final String sdl;
        final Consumer<GraphitronSchema> assertions;
        InputIdReferenceCase(String description, String sdl, Consumer<GraphitronSchema> assertions) {
            this.sdl = sdl;
            this.assertions = assertions;
        }
        @Override public String toString() { return name().toLowerCase().replace('_', ' '); }
    }

    @ParameterizedTest(name = "{0}")
    @EnumSource(InputIdReferenceCase.class)
    void inputIdReferenceShimClassification(InputIdReferenceCase tc) {
        tc.assertions.accept(TestSchemaHelper.buildSchema(tc.sdl, FIXTURE_CTX));
    }

    // ===== Same-table @nodeId filter =====

    /**
     * Same-table {@code [ID!] @nodeId(typeName: T)} where T maps to the input's own table.
     * Semantics: filter rows whose composite primary key matches one of the decoded node IDs;
     * a primary-key IN predicate, not a FK join. The classifier short-circuits before
     * {@code findUniqueFkToTable(t, t)} (which would always miss) and emits the post-R50
     * column-shaped successor: {@link InputField.ColumnField} (arity-1) or
     * {@link InputField.CompositeColumnField} (arity > 1) carrying
     * {@link CallSiteExtraction.NodeIdDecodeKeys.SkipMismatchedElement}.
     */
    enum InputSameTableNodeIdCase {
        SAME_TABLE_COMPOSITE_PK(
            "input `[ID!] @nodeId(typeName: \"Bar\")` on a `bar`-bound input → CompositeColumnField "
                + "with NodeIdDecodeKeys over composite PK columns",
            """
            type Bar implements Node @table(name: "bar") @node { id: ID! }
            input BarFilterInput @table(name: "bar") {
              ids: [ID!] @nodeId(typeName: "Bar")
            }
            type Query { x: String }
            """,
            schema -> {
                var tit = (GraphitronType.TableInputType) schema.type("BarFilterInput");
                var f = (InputField.CompositeColumnField) tit.inputFields().stream()
                    .filter(InputField.CompositeColumnField.class::isInstance).findFirst().orElseThrow();
                assertThat(f.list()).isTrue();
                assertThat(f.columns()).extracting(ColumnRef::sqlName)
                    .containsExactly("id_1", "id_2");
                assertThat(f.extraction())
                    .isInstanceOf(CallSiteExtraction.SkipMismatchedElement.class);
                var skip = (CallSiteExtraction.SkipMismatchedElement) f.extraction();
                assertThat(skip.decodeMethod().methodName()).isEqualTo("decodeBar");
            }),

        SAME_TABLE_SINGLE_PK(
            "single-PK same-table case → ColumnField with NodeIdDecodeKeys over the one key column",
            """
            type Baz implements Node @table(name: "baz") @node { id: ID! }
            input BazFilterInput @table(name: "baz") {
              ids: [ID!] @nodeId(typeName: "Baz")
            }
            type Query { x: String }
            """,
            schema -> {
                var tit = (GraphitronType.TableInputType) schema.type("BazFilterInput");
                var f = (InputField.ColumnField) tit.inputFields().stream()
                    .filter(InputField.ColumnField.class::isInstance).findFirst().orElseThrow();
                assertThat(f.list()).isTrue();
                assertThat(f.column().sqlName()).isEqualTo("id");
                assertThat(f.extraction())
                    .isInstanceOf(CallSiteExtraction.SkipMismatchedElement.class);
                var skip = (CallSiteExtraction.SkipMismatchedElement) f.extraction();
                assertThat(skip.decodeMethod().methodName()).isEqualTo("decodeBaz");
            }),

        SAME_TABLE_TARGET_NOT_NODE(
            "same-table reference where target table has no @node metadata → UnclassifiedType "
                + "(no PK columns to encode)",
            """
            type Qux @table(name: "qux") { name: String }
            input QuxFilterInput @table(name: "qux") {
              ids: [ID!] @nodeId(typeName: "Qux")
            }
            type Query { x: String }
            """,
            schema -> assertThat(schema.type("QuxFilterInput"))
                .isInstanceOf(GraphitronType.UnclassifiedType.class)),

        BARE_LIST_NODE_ID_INFERS_TYPE_NAME(
            "bare `[ID!] @nodeId` infers typeName from the unique @table-matching object type → "
                + "CompositeColumnField (same as explicit typeName)",
            """
            type Bar implements Node @table(name: "bar") @node { id: ID! }
            input BarFilterInput @table(name: "bar") {
              ids: [ID!] @nodeId
            }
            type Query { x: String }
            """,
            schema -> {
                var tit = (GraphitronType.TableInputType) schema.type("BarFilterInput");
                var f = (InputField.CompositeColumnField) tit.inputFields().stream()
                    .filter(InputField.CompositeColumnField.class::isInstance).findFirst().orElseThrow();
                assertThat(f.list()).isTrue();
                assertThat(f.columns()).extracting(ColumnRef::sqlName)
                    .containsExactly("id_1", "id_2");
                assertThat(f.extraction())
                    .isInstanceOf(CallSiteExtraction.SkipMismatchedElement.class);
            }),

        BARE_LIST_NODE_ID_NO_OBJECT_TYPE(
            "bare `[ID!] @nodeId` with no @table-matching object type → friendly inference error",
            """
            input BarFilterInput @table(name: "bar") {
              ids: [ID!] @nodeId
            }
            type Query { x: String }
            """,
            schema -> {
                var t = (GraphitronType.UnclassifiedType) schema.type("BarFilterInput");
                assertThat(t.reason())
                    .contains("@nodeId without typeName: cannot infer node type")
                    .contains("no @table-annotated object type maps to table 'bar'");
            }),

        BARE_LIST_NODE_ID_AMBIGUOUS(
            "bare `[ID!] @nodeId` with two @table-matching object types → friendly ambiguity error",
            """
            type BarA @table(name: "bar") @node { id: ID! }
            type BarB @table(name: "bar") @node { id: ID! }
            input BarFilterInput @table(name: "bar") {
              ids: [ID!] @nodeId
            }
            type Query { a: BarA b: BarB }
            """,
            schema -> {
                var t = (GraphitronType.UnclassifiedType) schema.type("BarFilterInput");
                assertThat(t.reason())
                    .contains("@nodeId without typeName: is ambiguous")
                    .contains("BarA")
                    .contains("BarB");
            });

        final String sdl;
        final Consumer<GraphitronSchema> assertions;
        InputSameTableNodeIdCase(String description, String sdl, Consumer<GraphitronSchema> assertions) {
            this.sdl = sdl;
            this.assertions = assertions;
        }
        @Override public String toString() { return name().toLowerCase().replace('_', ' '); }
    }

    @ParameterizedTest(name = "{0}")
    @EnumSource(InputSameTableNodeIdCase.class)
    void inputSameTableNodeIdClassification(InputSameTableNodeIdCase tc) {
        tc.assertions.accept(TestSchemaHelper.buildSchema(tc.sdl, FIXTURE_CTX));
    }

    // ===== Output side =====

    enum OutputCase {
        IMPLICIT_ID(
            "output `id: ID!` on a `implements Node @node` parent backed by a metadata-carrying "
                + "table → CompositeColumnField with NodeIdEncodeKeys (composite-PK Bar uses 2 columns)",
            """
            type Foo implements Node @table(name: "bar") @node { id: ID! }
            type Query { foo: Foo }
            """,
            schema -> {
                assertThat(schema.type("Foo")).isInstanceOf(GraphitronType.NodeType.class);
                var f = (ChildField.CompositeColumnField) schema.field("Foo", "id");
                assertThat(f.columns()).extracting(ColumnRef::sqlName)
                    .containsExactly("id_1", "id_2");
                assertThat(f.compaction().encodeMethod().methodName()).isEqualTo("encodeFoo");
            }),

        ACCESSOR_MISSING(
            "column absent AND no metadata → UnclassifiedField, parent stays TableType",
            """
            type Foo @table(name: "qux") { id: ID! }
            type Query { foo: Foo }
            """,
            schema -> {
                assertThat(schema.type("Foo")).isInstanceOf(GraphitronType.TableType.class);
                assertThat(schema.field("Foo", "id"))
                    .isInstanceOf(GraphitronField.UnclassifiedField.class);
            }),

        NODE_ID_DIRECTIVE_ON_NODE_TYPE(
            "`id: ID! @nodeId` on a `implements Node @node` parent → CompositeColumnField via the "
                + "@nodeId guard (canonical opt-in form; no synthesis from `@table` alone)",
            """
            type Foo implements Node @table(name: "bar") @node { id: ID! @nodeId }
            type Query { foo: Foo }
            """,
            schema -> {
                assertThat(schema.type("Foo")).isInstanceOf(GraphitronType.NodeType.class);
                var f = (ChildField.CompositeColumnField) schema.field("Foo", "id");
                assertThat(f.columns()).extracting(ColumnRef::sqlName)
                    .containsExactly("id_1", "id_2");
                assertThat(f.compaction().encodeMethod().methodName()).isEqualTo("encodeFoo");
            });

        final String sdl;
        final Consumer<GraphitronSchema> assertions;
        OutputCase(String description, String sdl, Consumer<GraphitronSchema> assertions) {
            this.sdl = sdl;
            this.assertions = assertions;
        }
        @Override public String toString() { return name().toLowerCase().replace('_', ' '); }
    }

    @ParameterizedTest(name = "{0}")
    @EnumSource(OutputCase.class)
    void outputNodeIdClassification(OutputCase tc) {
        tc.assertions.accept(TestSchemaHelper.buildSchema(tc.sdl, FIXTURE_CTX));
    }

    // ===== Lookup arg side (composite-PK NodeId @lookupKey) =====

    enum LookupKeyCase {
        SCALAR_NODEID_LOOKUP_COMPOSITE_PK(
            "scalar `id: ID @lookupKey` arg on a composite-PK NodeType-backed lookup → "
                + "CompositeColumnArg(ThrowOnMismatch) → projectForLookup lifts to DecodedRecord "
                + "with positional RecordBindings over the composite key columns (R50 phase g)",
            """
            type Bar implements Node @table(name: "bar") @node { id: ID! @nodeId name: String }
            type Query { barById(id: ID @lookupKey): Bar }
            """,
            schema -> {
                var f = (no.sikt.graphitron.rewrite.model.QueryField.QueryLookupTableField)
                    schema.field("Query", "barById");
                var cm = (no.sikt.graphitron.rewrite.model.LookupMapping.ColumnMapping) f.lookupMapping();
                assertThat(cm.args()).hasSize(1);
                var arg = (no.sikt.graphitron.rewrite.model.LookupMapping.ColumnMapping.LookupArg.DecodedRecord)
                    cm.args().get(0);
                assertThat(arg.argName()).isEqualTo("id");
                assertThat(arg.list()).isFalse();
                assertThat(arg.decodeMethod().methodName()).isEqualTo("decodeBar");
                assertThat(arg.bindings()).hasSize(2);
                assertThat(arg.bindings()).extracting(b -> b.targetColumn().sqlName())
                    .containsExactly("id_1", "id_2");
                assertThat(arg.bindings()).extracting(no.sikt.graphitron.rewrite.model.InputColumnBinding.RecordBinding::index)
                    .containsExactly(0, 1);
            }),

        LIST_NODEID_LOOKUP_COMPOSITE_PK(
            "list `ids: [ID!] @lookupKey` arg on a composite-PK NodeType-backed lookup → "
                + "DecodedRecord with list=true; each input id decodes once per row to drive "
                + "the VALUES + JOIN row-IN shape",
            """
            type Bar implements Node @table(name: "bar") @node { id: ID! @nodeId name: String }
            type Query { barsByIds(ids: [ID!] @lookupKey): [Bar!]! }
            """,
            schema -> {
                var f = (no.sikt.graphitron.rewrite.model.QueryField.QueryLookupTableField)
                    schema.field("Query", "barsByIds");
                var cm = (no.sikt.graphitron.rewrite.model.LookupMapping.ColumnMapping) f.lookupMapping();
                var arg = (no.sikt.graphitron.rewrite.model.LookupMapping.ColumnMapping.LookupArg.DecodedRecord)
                    cm.args().get(0);
                assertThat(arg.list()).isTrue();
                assertThat(arg.bindings()).hasSize(2);
            }),

        SCALAR_NODEID_NON_LOOKUP_COMPOSITE_PK_DEFERRED(
            "scalar `id: ID @nodeId` arg without `@lookupKey` on a composite-PK NodeType is not "
                + "yet wired (mutation-key + top-level filter paths land in a later R50 slice); "
                + "surfaces as UnclassifiedField at the surrounding query field",
            """
            type Bar @table(name: "bar") { id: ID! @field(name: "ID_1") }
            type Query { bar(id: ID): Bar }
            """,
            schema -> {
                var f = schema.field("Query", "bar");
                assertThat(f).isInstanceOf(no.sikt.graphitron.rewrite.model.GraphitronField.UnclassifiedField.class);
                var uf = (no.sikt.graphitron.rewrite.model.GraphitronField.UnclassifiedField) f;
                assertThat(uf.reason()).contains("composite-PK NodeType");
            });

        final String sdl;
        final Consumer<GraphitronSchema> assertions;
        LookupKeyCase(String description, String sdl, Consumer<GraphitronSchema> assertions) {
            this.sdl = sdl;
            this.assertions = assertions;
        }
        @Override public String toString() { return name().toLowerCase().replace('_', ' '); }
    }

    @ParameterizedTest(name = "{0}")
    @EnumSource(LookupKeyCase.class)
    void lookupKeyClassification(LookupKeyCase tc) {
        tc.assertions.accept(TestSchemaHelper.buildSchema(tc.sdl, FIXTURE_CTX));
    }

    // ===== R50 phase (g-B): rooted-at-parent single-hop reference =====
    //
    // child_ref.parent_alt_key references parent_node.alt_key (the *non-PK* unique column);
    // ParentNode's __NODE_KEY_COLUMNS pins the keyColumn to PK_ID. The FK target column does not
    // positionally match the keyColumn, so fkMirrorSourceColumns returns null and the classifier
    // routes through the rooted-at-parent JOIN-with-projection path: a ColumnReferenceField
    // whose column is the parent's keyColumn (read from the joined parent_node) and whose
    // joinPath carries the single FK hop. See lift-nodeid-out-of-model.md "Variant-by-variant
    // collapse → Single-hop emission, two shapes".

    @Test
    void rootedAtParent_nonMirrorFk_resolvesToColumnReferenceField() {
        var schema = TestSchemaHelper.buildSchema("""
            type ParentNode implements Node @table(name: "parent_node") @node {
                id: ID! @nodeId
                altKey: String! @field(name: "alt_key")
                name: String
            }
            type ChildRef @table(name: "child_ref") {
                childId: String! @field(name: "child_id")
                parentNodeId: ID @nodeId(typeName: "ParentNode")
                    @reference(path: [{key: "child_ref_parent_alt_key_fkey"}])
            }
            type Query { childRefs: [ChildRef!]! }
            """, FIXTURE_CTX);

        var f = (ChildField.ColumnReferenceField) schema.field("ChildRef", "parentNodeId");
        // Projected column is ParentNode's keyColumn (pk_id), not the FK target (alt_key);
        // emitter must read it through the joined parent_node alias.
        assertThat(f.column().sqlName()).isEqualTo("pk_id");
        // Single-hop FK chain — child_ref → parent_node — drives the JOIN-with-projection path.
        assertThat(f.joinPath()).hasSize(1);
        // NodeId encode call: per-type encoder helper resolved at classify time.
        var enc = (CallSiteCompaction.NodeIdEncodeKeys) f.compaction();
        assertThat(enc.encodeMethod().methodName()).isEqualTo("encodeParentNode");
        assertThat(enc.encodeMethod().paramSignature())
            .extracting(ColumnRef::sqlName)
            .containsExactly("pk_id");
    }
}
