package no.fellesstudentsystem.graphitron.definitions.sql;

/**
 * SQL join condition which joins on a single key generated by jOOQ, referred to by name.
 */
public class SQLJoinOnKey extends SQLJoinField {
    private final static String JOOQ_METHOD_CALL = "onKey";
    private final static int orderingPriority = 0; // onKey MUST be first.
    private final String key;

    /**
     * @param key The name of a key generated by jOOQ.
     */
    public SQLJoinOnKey(String key) {
        this.key = key;
    }

    /**
     * @return jOOQ name of the key.
     */
    public String getKey() {
        return key;
    }

    public int getOrderingPriority() {
        return orderingPriority;
    }

    @Override
    public String getMethodCallName() {
        return JOOQ_METHOD_CALL;
    }

    @Override
    public String toJoinString(String joinSourceTable, String aliasName) {
        return getKey();
    }
}
