on:
  push:
    paths:
      - graphitron-codegen-parent/graphitron-java-codegen/README.md
      - graphitron-example/README.md
      - graphitron-schema-transform/README.md
name: TOC Generator
jobs:
  generateTOC:
    name: TOC Generator
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v4
        with:
          TARGET_PATHS: graphitron-codegen-parent/graphitron-java-codegen/README.md, graphitron-example/README.md, graphitron-schema-transform/README.md