on:
  push:
    branches:
      - main
    paths:
      - graphitron-codegen-parent/graphitron-java-codegen/README.md
      - graphitron-example/README.md
      - graphitron-schema-transform/README.md
name: TOC Generator
jobs:
  generateTOC:
    name: TOC Generator
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate TOC
        uses: technote-space/toc-generator@v4
        with:
          TARGET_PATHS: graphitron-codegen-parent/graphitron-java-codegen/README.md, graphitron-example/README.md, graphitron-schema-transform/README.md
          CREATE_PR: true
          PR_BRANCH_PREFIX: toc-update
          PR_TITLE: "Automatic Update of table of contents"
          PR_BODY: |
            This PR automatically updates the table of contents in README files.
